Add dApps prerequisites
casper-network/docs pull request #1048
Opened 2023-04-08 21:18 UTC by andrzej-casper

### What does this PR introduce?

New dApp page "Prerequisites".

### Additional context

These changes are backported from the default branch of [docs-new](https://github.com/casper-network/docs-new) repository, so you can preview them [live here](https://staging.docs.casper.network/developers/dapps/prerequisites/).

Original PR authored by @dylanireland: https://github.com/casper-network/docs-new/pull/141.

### Checklist

- [x] Docs are successfully building - `yarn install && yarn run build`.
- [x] All technical procedures have been tested.

2023-04-12 11:50 UTC, andrzej-casper commented
This is quite important, because _DevPortal_ homepage is leading to this page, which is under construction:

![image](https://user-images.githubusercontent.com/121791569/231448309-96f792e6-4cf6-4466-9d3e-4b06a3aca7e7.png)

![image](https://user-images.githubusercontent.com/121791569/231448405-d66601ef-295b-4f9c-a8b7-cec256c6d030.png)

2023-04-12 13:55 UTC, ACStoneCL requested changes

2023-04-12 13:55 UTC, ACStoneCL commented on source/docs/casper/developers/dapps/prerequisites.md
> +4. Plan for upgrades and bug fixes: Design your smart contracts to take advantage of Casper Network's support for smart contract upgradability. By doing so, you can ensure that your dApp remains secu
```suggestion
4. Plan for upgrades and bug fixes: Design your smart contracts to take advantage of Casper's support for smart contract upgradability. By doing so, you can ensure that your dApp remains secure and adaptable as the Casper ecosystem evolves, enabling seamless integration of future upgrades and bug fixes.
```

2023-04-14 13:55 UTC, Adrian-Wrona commented
I changed the link on the DevPortal yesterday. I'll bring it back once this is approved

2023-04-17 05:04 UTC, dylanireland commented
Grammatical changes approved. Requesting final review @ACStoneCL

2023-04-17 14:54 UTC, ACStoneCL approved these changes
Issues have been addressed, LGTM.

2023-04-18 14:36 UTC, merged