Rewrote monitor & consume events
casper-network/docs pull request #1058
Opened 2023-04-12 12:06 UTC by andrzej-casper

### What does this PR change?

Rewrote Build-dApps/Monitor-and-Consume-Events.

### Additional context

These changes are backported from the default branch of [docs-new](https://github.com/casper-network/docs-new) repository, so you can preview them [live here](https://staging.docs.casper.network/developers/dapps/monitor-and-consume-events/).

Original PR authored by @dylanireland: https://github.com/casper-network/docs-new/pull/181.

### Checklist

- [x] I ran the docs locally using `yarn install` and `yarn run start`.
- [x] All links (internal and external) have been verified.
- [x] All technical procedures have been tested.

2023-04-12 14:50 UTC, ipopescu requested changes
@dylanireland, thanks for the content!
I spoke about this PR with @ACStoneCL and @darthsiroftardis, and we'd like to keep the curl statements as well. Is it possible to use different tabs to keep the original content we had on the page?

2023-04-17 05:35 UTC, dylanireland commented
cURL documentation re-added in multilingual code blocks / tabs. Requesting review:
@ipopescu 
@ACStoneCL 
@darthsiroftardis

2023-04-27 11:07 UTC, ipopescu commented
To proceed with this PR:
- @dylanireland @andrzej-casper @ACStoneCL, please review PR #1108.
- @hoffmannjan, please review the technical code blocks or re-assign the review to someone on the team.

Also, note that much of this content will need to be replaced once the SSE sidecar is released. The sidecar is already running in production in beta mode with some validators. We will be discouraging users to connect to the node directly.

"The Casper Event Sidecar is an application that runs in tandem with the node process. This reduces the load on the node process by allowing subscribers to monitor the event stream through the Sidecar while the node focuses entirely on the blockchain."

Thank you!

2023-05-08 21:41 UTC, dylanireland commented
LGTM. Requesting review from @hoffmannjan and @ACStoneCL

2023-05-22 13:40 UTC, ACStoneCL reviewed
A few small nits, but otherwise this LGTM - but with the caveat that @ipopescu mentioned about Sidecar ideally supplanting most direct connections.

Will leave final approval to @hoffmannjan or whoever performs the final tech review.

2023-05-22 13:40 UTC, ACStoneCL commented on source/docs/casper/developers/dapps/monitor-and-consume-events.md
> +Applications can listen for such events for a specific account during a particular era, containing certain data. Then, they can parse the data and discard what is not needed. To consume the event str
```suggestion
Applications can listen for such events for a specific account during a particular era, containing certain data. Then, they can parse the data and discard what they do not need. To consume the event stream, set up an event listener in your dApp using the following code:
```

2023-05-22 13:40 UTC, ACStoneCL commented on source/docs/casper/developers/dapps/monitor-and-consume-events.md
> +  <summary>Expand to view output</summary>
```suggestion
<summary>Expand to view output</summary>
```

2023-05-22 13:40 UTC, ACStoneCL commented on source/docs/casper/developers/dapps/monitor-and-consume-events.md
> +This event indicates that the final approvals from validators are signed, and further alterations to the block will not be allowed. Refer to the [consensus reached](../../concepts/deploy-and-deploy-l
```suggestion
This event indicates validators have signed the final approvals and further alterations to the block will not be allowed. Refer to the [consensus reached](../../concepts/deploy-and-deploy-lifecycle.md#consensus-reached) and [block finality](../../concepts/glossary/B.md#block-finality) sections to learn more about finality signatures. 
```

2023-05-31 14:16 UTC, andrzej-casper commented
@ipopescu Build fixed by merging latest `dev`.

2023-06-06 16:11 UTC, ipopescu approved these changes
LGTM!

2023-06-21 13:56 UTC, hoffmannjan approved these changes
LGTM, only two nitpicks to use more current syntax :)

2023-06-21 13:56 UTC, hoffmannjan commented on source/docs/casper/developers/dapps/monitor-and-consume-events.md
> +}
```suggestion
const eventHandler = (event) => {
    console.log(event)
}
```

2023-06-21 13:56 UTC, hoffmannjan commented on source/docs/casper/developers/dapps/monitor-and-consume-events.md
> +}
lets use arrow function everywhere as this is current standard for ES6

2023-06-21 13:56 UTC, hoffmannjan commented on source/docs/casper/developers/dapps/monitor-and-consume-events.md
> +  }
```suggestion
const eventHandler = (event) => {
  if (event.body.DeployAccepted.header.account == "012481699f9231e36ecf002675cd7186b48e6a735d10ec1b30f587ca716937752c") {
    // Perform an action
  }
```

2023-06-27 16:13 UTC, andrzej-casper commented
@dylanireland Build fixed by merging latest `dev`. PR ready for merge :rocket:!

2023-06-27 18:41 UTC, merged