CEP18 / ERC20 - initial commit
casper-network/docs pull request #1164
Opened 2023-06-19 15:21 UTC by KMCreatesWorlds

### What does this PR fix/introduce?
This PR introduces the tutorial for CEP18 / ERC20.

### Additional context
The PR tries to explain the ERC20 Standard and how the CEP18 implementation of the standard was made.
It explains the implications of using many ERC20 standards and shows how a deploy of a CEP18 based token can be made.

### Checklist
(Delete any that aren't relevant)

- [ ] Docs are successfully building - `yarn install && yarn run build`.
- [ ] For new **internal** links I used *relative file paths* (with .md extension) - e.g. `../../faq/faq-general.md` - instead of introducing *absolute file path*, or *relative/absolute URL*.
- [ ] All external links have been verified with `yarn run check:externals`.

### Reviewers
@caspermel

2023-06-19 19:47 UTC, melpadden commented on source/docs/casper/resources/tutorials/beginner/cep18.md
> +Make sure you have installed the software/packages needed for this tutorial.
What are the packages required? Or is it just the basic requirements? In which case just link back to the "install prerequisites" page as usual.

2023-06-19 19:56 UTC, melpadden requested changes
Couple of typos, otherwise fine.

2023-06-19 19:56 UTC, melpadden commented on source/docs/casper/resources/tutorials/beginner/cep18.md
> +The `keys` folder is not a part of the CEP18 folder structure. Optionaly you should provide a folder where your keys are stored.
```suggestion
The `keys` folder is not a part of the CEP18 folder structure. Optionally you should provide a folder where your keys are stored.
```

2023-06-19 19:56 UTC, melpadden commented on source/docs/casper/resources/tutorials/beginner/cep18.md
> +The response from the `put-deploy` command is as follows:
```suggestion
The response from the `put-deploy` command should look like this:
```

2023-06-19 19:56 UTC, melpadden commented on source/docs/casper/resources/tutorials/beginner/cep18.md
> +Be always mindful of the payment amount during the deploy process. If the amount is to small, then the deploy will fail with `Out of gas error`.
```suggestion
Be always mindful of the payment amount during the deploy process. If the amount is too small, then the deploy will fail with `Out of gas error`.
```

2023-06-22 19:59 UTC, ACStoneCL requested changes

2023-06-22 19:59 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/beginner/cep18.md
> +## ERC-20 implementations on Casper and implications for DEXes {#erc20-implications}
```suggestion
## ERC-20 Implementations on Casper and Implications for Decentralized Exchanges {#erc20-implications}
```

2023-06-22 19:59 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/beginner/cep18.md
> +-	Interoperability – different implementations of the ERC-20 standard can hinder seamless integration between tokens, dApp, or wallets.
```suggestion
-	Interoperability – Different implementations of the ERC-20 standard can hinder seamless integration between tokens, dApps or wallets.
```

2023-06-22 19:59 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/beginner/cep18.md
> +-	Project Security Audits – well-established standards usually undergo a thorough security audit. This ensures a higher level of security and reduces the risk of vulnerabilities.
```suggestion
-	Project Security Audits – Well-established standards usually undergo a thorough security audit. This ensures a higher level of security and reduces the risk of vulnerabilities.
```

2023-06-22 19:59 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/beginner/cep18.md
> +-	Ecosystem – The longer a Blockchain network exists, the more widespread a standard implementation like ERC-20 is. Using a different implementation may limit availability of supported projects and m
```suggestion
-	Ecosystem – The longer a blockchain network exists, the more widespread a standard implementation like ERC-20 becomes. Using a different implementation may limit availability of supported projects and require additional effort for integration.
```

2023-06-22 19:59 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/beginner/cep18.md
> +It is generally advisable to use a single well-established implementation of the standard and for this purpose the CEP-18 Standard was created.
```suggestion
The CEP-18 Casper Fungible Token Standard establishes a single implementation of the ERC-20 Standard for Casper networks to avoid disparities and incompatibilities.
```

2023-06-22 19:59 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/beginner/cep18.md
> +The CEP-18 Token Standard is the Casper Network compliant implementation and provides the following contract methods to interact with the token contract:
```suggestion
The CEP-18 Token Standard is a Casper network compliant implementation of ERC-20 that provides the following contract methods to interact with the token contract:
```

2023-06-22 19:59 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/beginner/cep18.md
> + - allowance - Returns the amount of owner’s tokens allowed to be spent by the spender
```suggestion
 - `allowance` - Returns the amount of owner’s tokens allowed to be spent by the spender
```

2023-06-22 19:59 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/beginner/cep18.md
> + - approve - Allows a spender to transfer up to an amount of the direct caller’s tokens
```suggestion
 - `approve` - Allows a spender to transfer up to an amount of the direct caller’s tokens
```

2023-06-22 19:59 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/beginner/cep18.md
> + - balance_of - Returns the token balance of the owner
```suggestion
 - `balance_of` - Returns the token balance of the owner
```

2023-06-22 19:59 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/beginner/cep18.md
> + - decimals - Returns the decimals of the token
```suggestion
 - `decimals` - Returns the decimal places applied to the balance of the token
```

2023-06-22 19:59 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/beginner/cep18.md
> + - name - Returns the name of the token
```suggestion
 - `name` - Returns the name of the token
```

2023-06-22 19:59 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/beginner/cep18.md
> + - symbol - Returns the symbol of the token
```suggestion
 - `symbol` - Returns the symbol of the token
```

2023-06-22 19:59 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/beginner/cep18.md
> + - total_supply - Returns the total supply of the token
```suggestion
 - `total_supply` - Returns the total supply of the token
```

2023-06-22 19:59 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/beginner/cep18.md
> + - transfer - Transfers an amount of tokens from the direct caller to a recipient
```suggestion
 - `transfer` - Transfers an amount of tokens from the direct caller to a recipient
```

2023-06-22 19:59 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/beginner/cep18.md
> + - transfer_from - Transfers an amount of tokens from the owner to a recipient, if the direct caller has been previously approved to spend the specified amount on behalf of the owner
```suggestion
 - `transfer_from` - Transfers an amount of tokens from the owner to a recipient, if the direct caller has been previously approved to spend the specified amount on behalf of the owner
```

2023-06-22 19:59 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/beginner/cep18.md
> +To understand how the methods work in detail, it is advisable to check the reference implementation on the [GitHub](https://github.com/casper-ecosystem/cep18).
```suggestion
For more detail on these methods, there is a reference implementation available on [GitHub](https://github.com/casper-ecosystem/cep18). 
```

2023-06-22 19:59 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/beginner/cep18.md
> +## Creating a CEP-18 Token on the test-net {#cep18-testnet}
```suggestion
## Creating a CEP-18 Token on the Testnet {#cep18-testnet}
```

2023-06-22 19:59 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/beginner/cep18.md
> +### Clone and Compile the CEP-18 contract {#cep18-contract-clone}
```suggestion
### Clone and Compile the CEP-18 Contract {#cep18-contract-clone}
```

2023-06-22 19:59 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/beginner/cep18.md
> +Since we already understand how the CEP-18 standard is constructed, we will be installing our own token contract in the Global State.
```suggestion
Building on the construction of a CEP-18 token as explained above, we will be installing our own token contract in global state.
```

2023-06-22 19:59 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/beginner/cep18.md
> +We will clone the token repository and prepare the token contract for the deployment.
```suggestion
We will clone the token repository and prepare the token contract for sending in a Deploy.
```

2023-06-22 19:59 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/beginner/cep18.md
> +If the `build-contract` finishes with an error `wasm-strip: command not found`, make sure you install an additional package:
This command is only for Macs, correct? If so, that should be specified to avoid confusion.

2023-06-22 19:59 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/beginner/cep18.md
> +### Install the CEP-18 contract {#cep18-contract-install}
```suggestion
### Install the CEP-18 Contract {#cep18-contract-install}
```

2023-06-22 19:59 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/beginner/cep18.md
> +It is important to understand the costs related with performing the deploys. You should try doing few deploys on the Testnet to familiarize yourself, what costs should be expected.
```suggestion
As it is important to understand the potential costs of your Deploy, you should send several on Testnet to familiarize yourself before sending a Deploy to Mainnet.
```

2023-06-22 19:59 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/beginner/cep18.md
> +- Explained the ERC20 standard and what the implications for not using the standard implementations are.
```suggestion
- Explained the ERC20 standard and what the implications are for not using the standard implementations.
```

2023-06-22 19:59 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/beginner/cep18.md
> +- Developed a CEP18 Rust contract on a Casper network and defined the proper arguments for the deploy.
```suggestion
- Developed a CEP-18 Rust contract on a Casper network and defined the proper arguments for the deploy.
```

2023-06-26 09:13 UTC, KMCreatesWorlds commented on source/docs/casper/resources/tutorials/beginner/cep18.md
> +Make sure you have installed the software/packages needed for this tutorial.
Basic prerequisites have been linked

2023-06-28 16:42 UTC, ACStoneCL approved these changes

2023-06-28 18:42 UTC, andrzej-casper commented
@KMCreatesWorlds During merge I restored _Casper CEP-18 Client_ link.

2023-07-03 12:41 UTC, melpadden approved these changes

2023-07-03 12:48 UTC, merged