1176 - Migrate from other chains
casper-network/docs pull request #1178
Opened 2023-06-26 15:26 UTC by KMCreatesWorlds

### What does this PR fix/introduce?
This PR introduces the overview of how the move from some blockchains can be made to Casper.

### Additional context
The PR gives insight into Ethereum, Near, Solana, and Aptos and how they compare to Casper regarding aspects such as Contract Lifecycle, State Management, or how to interact with the Contract.

This is not a comprehensive explanation of how the migration of a Contract for example on Ethereum can be made on Casper, but instead gives high-level hints on how to approach the individual aspects to make the move to Casper easier. 

### Checklist

- [ ] Docs are successfully building - `yarn install && yarn run build`.
- [ ] For new **internal** links I used *relative file paths* (with .md extension) - e.g. `../../faq/faq-general.md` - instead of introducing *absolute file path*, or *relative/absolute URL*.
- [ ] All external links have been verified with `yarn run check:externals`.

### Reviewers
@caspermel

2023-07-04 11:11 UTC, ipopescu requested changes
Thanks for putting this together! Not an easy document to write, so it needs a bit more polishing.

I have submitted a thorough editing pass with PR #1183. Please take a look at this first. After reviewing my updates, please rename the file to moving-to-casper.md to remove any ambiguity with the word “migrate”.

In addition, I have a few more requests.

Please try to remove repeated explanations in the five categories you defined (lifecycle, storage, methods etc.). For example, we are referencing Named Keys and Dictionaries three times. Resources are defined twice. 

State management can be combined with storage, actually. If you want to keep them separate, try to find another way to organize the content so there is less duplication.

I would like to see more links to coding examples. There are some, but many sections seem theoretical. You could link to any relevant topics (either in the Casper docs or externally). 
For example, when explaining get_key, at a minimum, link to [docs.rs](https://docs.rs/casper-contract/latest/casper_contract/contract_api/runtime/fn.get_key.html). Also, point to the reading-and-writing-to-the-blockchain.md file. 
This request applies to all concepts and explanations introduced.

Finally, a little more structure would be needed. For example, what are the comparison points in each tab? Are they covered for each blockchain?

2023-07-04 11:11 UTC, ipopescu commented on source/docs/casper/resources/migrate.md
> +The variables can be stored either as Named Keys or [Dictionaries](../concepts/dictionaries.md). Additionally, local variables are available within the entry points and can be utilized to perform nec
Local or global? I don’t think local is correct. Dev input needed.

2023-07-04 11:11 UTC, ipopescu commented on source/docs/casper/resources/migrate.md
> +casper-client put-deploy \
Link to the page where you got this example, so the reader can have more context if needed.

2023-07-04 11:11 UTC, ipopescu commented on source/docs/casper/resources/migrate.md
> +let uref: URef = runtime::get_key(Key_Name)
Match with the above example and include some more code context. As it stands, it doesn’t seem enough. Perhaps point to an example contract.

2023-07-23 17:34 UTC, KMCreatesWorlds commented on source/docs/casper/resources/migrate.md
> +Near smart contracts can be written in either JavaScript or Rust. Regardless of the chosen language, the Near SDK compiles the code to WebAssembly. In the Near ecosystem, smart contracts function as
This is a fair point, trying to make the text more compact, I skipped one sentence, where the SDK packs the code with a lightweight runtime and this then is compiled into the WebAssembly. Has been corrected in the docs.

2023-07-23 17:35 UTC, KMCreatesWorlds commented on source/docs/casper/resources/migrate.md
> +The Aptos programming language is known as Move. Its primary concepts revolve around scripts and modules. Scripts enable developers to incorporate additional logic into transactions, while modules al
I have renamed the whole paragraph to be more about "Smart Contract Platform Overview" I think this is more fitting, as we are not trying to show the lifecycle in all of the Blockchains, but give the overview of the platforms.

2023-07-23 17:36 UTC, KMCreatesWorlds commented on source/docs/casper/resources/migrate.md
> +## Contract Lifecycle{#contract-lifecycle}
Agreed, was renamed to "Smart Contract Platform Overview".

2023-07-23 17:50 UTC, KMCreatesWorlds commented on source/docs/casper/resources/migrate.md
> +## Public Methods{#public-methods}
Agreed, there are some difficulties in consolidating the concepts since all are similar but depending on the Blockchain either a function or method is being used. I have used "functions" where applicable and left "methods" for Blockchains like Ethereum. 
The paragraph was renamed to "Contract Functions".

2023-07-23 17:58 UTC, KMCreatesWorlds commented on source/docs/casper/resources/migrate.md
> +The variables can be stored either as Named Keys or [Dictionaries](../concepts/dictionaries.md). Additionally, local variables are available within the entry points and can be utilized to perform nec
Local is correct. Assuming, that we can define "let key_name = String::from(COUNT_KEY);" inside an Entry Point, this would be considered a local variable in the context of an Entry Point and can be used for example in "counter_named_keys.insert(key_name, count_start.into());".

2023-07-23 18:05 UTC, KMCreatesWorlds commented on source/docs/casper/resources/migrate.md
> +casper-client put-deploy \
The has been linked.

2023-07-23 18:17 UTC, KMCreatesWorlds commented on source/docs/casper/resources/migrate.md
> +let uref: URef = runtime::get_key(Key_Name)
The appropriate resources have been linked.

2023-07-23 18:19 UTC, KMCreatesWorlds commented on source/docs/casper/resources/migrate.md
> +Strongly typed function arguments require explicit definition of both the input and return variables.
That is true however, each blockchain has similar capabilities in this regard. As we divide the explanations per Blockchain, the repeated content can't be really avoided. This shouldn't pose that much problem since each Blockchain is in a separate tab. If it's ok, it would be good to leave it as it is after the editing pass.

2023-07-23 18:23 UTC, KMCreatesWorlds commented on source/docs/casper/resources/migrate.md
> +Casper smart contracts are written in Rust. In Casper, variables defined within the smart contract can be stored as either Named Keys or [Dictionaries](../concepts/dictionaries.md). The `call` functi
This is true, that the section was repeated. I wouldn't necessarily remove it from here, as "Smart Contract Overview" would be the primary point of information for someone reading this part.

2023-07-26 10:54 UTC, ipopescu commented
@KMCreatesWorlds @andrzej-casper Acknowledging the review request.

2023-08-08 21:09 UTC, ipopescu commented
@KMCreatesWorlds, please address or respond to my requests from the previous review feedback. The document still needs some polishing. Summarizing my previous feedback here:

- rename the file to moving-to-casper.md to remove ambiguity with the word “migrate”
- try to remove repeated explanations in the five categories you defined (lifecycle, storage, methods, etc.). For example, we are referencing Named Keys and Dictionaries three times. Resources are defined twice.
- combine state management with storage; or try to find another way to remove duplication
- add cross-links to each topic in the Casper docs or link out to coding examples when introducing a concept/feature
- try to add the same structure in each tab. What are the comparison points in each tab? Are they covered for each blockchain?

cc @andrzej-casper @melpadden

2023-08-25 08:25 UTC, Adrian-Wrona commented
@KMCreatesWorlds could you take a look at @ipopescu review feedback?

2023-09-13 17:18 UTC, ipopescu reviewed
Thanks for the updates, @KMCreatesWorlds. 
Here are a few minor edit requests. From the previous feedback, I see the following have been addressed - thanks!
- Renamed file to moving-to-casper.md
- Combined state management with storage
- Removed repeated definitions (Resouces, Named Keys, Dictionaries)

Let's discuss the following on the live call:
- Cross-links to each topic in the Casper docs or link out to coding examples
- Tab structure. What are the comparison points in each tab? Are they covered for each blockchain?

cc @ACStoneCL

2023-09-13 17:21 UTC, ipopescu commented on source/docs/casper/resources/moving-to-casper.md
> +title: Moving to Casper
Please update the title to match the rest in this section.

```suggestion
title: Move to Casper
```

2023-09-13 17:22 UTC, ipopescu commented on config/sidebar.config.js
> +        "resources/moving-to-casper",
I would move this higher, perhaps after `build-on-casper`.
Also, the table on the resouces/index.md page needs to be updated with this topic (the table matches the left nav order).

2023-09-14 17:28 UTC, ipopescu commented
> Let's discuss the following on the live call:
> 
> * Cross-links to each topic in the Casper docs or link out to coding examples
> * Tab structure. What are the comparison points in each tab? Are they covered for each blockchain?
> 
> cc @ACStoneCL

Karol and I spoke and we are on the same page. We have cross-links for Casper, but we won't add links on the other tabs. Developers coming from other protocols should already be familiar with them.
Finally, the tabs have structure, but not every topic is a 1-to-1 mapping. This is ok.

2023-09-15 12:27 UTC, ipopescu approved these changes
I ran this locally and it looks great. Thank you, @KMCreatesWorlds!

2023-09-15 13:25 UTC, merged