1259 aws nodes
casper-network/docs pull request #1296
Opened 2023-09-30 00:19 UTC by jdpinedac

### What does this PR fix/introduce?

- Fix redaction and typos
- Update IaC devcontainer structure and handling
- Update and refactor of NOT_VPN to VPN_USE environment variable
- Modules reorganization and fix redaction
- Refactor OpenVPN configuration procedure
- Add IaC devcontainer troubleshooting.
- Add a VSCode devcontainer to build and test the documentation.

### Additional context

This Pull Request enhances the documentation for deploying a Casper node on AWS Cloud. Several updates were made to the existing documentation, including managing the VPN server, the included devcontainer for using infrastructure as code, among other elements, in addition to correcting wording and some typos. A devcontainer was also incorporated for the documentation itself.

### Checklist
(Delete any that aren't relevant)

- [x] Docs are successfully building - `yarn install && yarn run build`.
- [x] For new **internal** links I used *relative file paths* (with .md extension) - e.g. `../../faq/faq-general.md` - instead of introducing *absolute file path*, or *relative/absolute URL*.
- [x] All external links have been verified with `yarn run check:externals`.
- [x] My changes follow the [Casper docs style guidelines](https://docs.casper.network/resources/contribute-to-docs/).
- [x] All technical procedures have been tested (if you want help with this, mention it in [Reviewers](#reviewers)).
- [x] If structural changes are introduced (not just content changes), cross-broswer testing has been completed.

### Reviewers
@ipopescu

2023-10-03 09:30 UTC, ipopescu commented
@jdpinedac, thank you! I started the review.

2023-10-03 09:39 UTC, ipopescu commented on .devcontainer/devcontainer.json
> +	"postCreateCommand": "sudo apt update; sudo apt install -y libnss3-dev libatk1.0-dev libatk-bridge2.0-dev libcups2-dev libdrm-dev libxkbcommon-dev libxcomposite-dev libxdamage-dev libxrandr-dev libg
FYI @bradjohnl

2023-10-03 09:41 UTC, ipopescu commented
@bradjohnl, please also do a technical review.

2023-10-03 09:41 UTC, bradjohnl approved these changes

2023-10-03 09:56 UTC, ipopescu commented
Do not merge until the https://github.com/casper-ecosystem/casper-node-on-cloud/ repository is public.

2023-10-03 13:43 UTC, ipopescu requested changes
The new content is very clear and well written. Thank you, @jdpinedac!
I submitted a few yet minor change requests and re-requested a technical review from Luca. 
Let's not merge this PR with the main docs until the repository becomes public. Please remove the old wiki content from the repo as well. A few things to really note though:
- Use dev container not devcontainter, and introduce it initially. Please update all ocurrences of ‘devcontainer’, unless referring to the actual file.
- Please check the missing command in the open-vpn.md file.
- Add higher-res screenshots in the open-vpn.md file please.

2023-10-03 13:43 UTC, ipopescu commented on source/docs/casper/operators/aws-nodes/4-modules.md
>  | mem_used               | RAM usage in GB           |
Please update this table. Casper and the beginning of the description needs to be capitalized. Finally, to match the style, we need a colon at the end of each description. "Disk usage percentage." is probably better than "Disk usage in percentage."

| casper-node logs       | Casper service logs.       |
| casper-node error logs | Casper service error logs. |
| disk_total             | Disk total capacity.       |
| disk_used              | Disk usage in GB.          |
| disk_percent           | Disk usage percentage. |

2023-10-03 13:43 UTC, ipopescu commented on source/docs/casper/operators/aws-nodes/4-modules.md
> +### Cloudwatch Logs
Please check the spelling to match the brand.
```suggestion
### CloudWatch Logs
```

2023-10-03 13:43 UTC, ipopescu commented on source/docs/casper/operators/aws-nodes/4-modules.md
Can we get an updated screenshot (email-notification.png) and remove the AWS highlighting? This one is over a year old.

2023-10-03 13:43 UTC, ipopescu commented on source/docs/casper/operators/aws-nodes/4-modules.md
> +All modules pertinent to overseeing the node. AWS offers a suite of services enabling operators to observe both the node and Casper service status. These services allow the establishment of alarms an
```suggestion
Monitoring modules are pertinent to overseeing the node. AWS offers a suite of services enabling operators to observe the node and Casper service status. These services allow the establishment of alarms and provide a visual representation on a dashboard, displaying the node's resources and capacity in real-time.
```

2023-10-03 13:43 UTC, ipopescu commented on source/docs/casper/operators/aws-nodes/4-modules.md
> +The IaC establishes a dashboard to oversee all pertinent resources. This dashboard displays connectivity status, blockchain metrics like block height, block time, and era count, along with node metri
```suggestion
The IaC establishes a dashboard to oversee all pertinent resources. This dashboard displays connectivity status, blockchain metrics like block height, block time, and era count, and node metrics including CPU, memory, and disk usage.
```

2023-10-03 13:43 UTC, ipopescu commented on source/docs/casper/operators/aws-nodes/4-modules.md
> +| `files/genSnapshot.sh`      | Bash file contains configurations to create a snapshot volume in EBS, with a cronjob performing backups every week. |
```suggestion
| `files/genSnapshot.sh`      | Bash file contains configurations to create a snapshot volume in EBS, with a cronjob performing weekly backups. |
```

2023-10-03 13:43 UTC, ipopescu commented on source/docs/casper/operators/aws-nodes/4-modules.md
> +| Zip Creation Module  | Module to compress information related to synthetic canary. |
```suggestion
| Zip Creation Module  | Module to compress information related to the synthetic canary. |
```

2023-10-03 13:43 UTC, ipopescu commented on source/docs/casper/operators/aws-nodes/4-modules.md
> +Modules to assist in information manipulation.
```suggestion
The following modules assist in data management.
```

2023-10-03 13:43 UTC, ipopescu commented on source/docs/casper/operators/aws-nodes/4-modules.md
> +Modules related to configuring the diverse network elements necessary for the node's proper functioning.
Please use full sentences.
```suggestion
Network modules configure diverse network elements necessary for the node to function correctly.
```

2023-10-03 13:43 UTC, ipopescu commented on source/docs/casper/operators/aws-nodes/4-modules.md
> +The OpenVPN Service provides the administrators a private and secure connection to the node. This simple VPN is available for five administrators. To configure the VPN server, read the [OpenVPN guide
```suggestion
The OpenVPN Service provides administrators with a private and secure connection to the node. This simple VPN is available for five administrators. To configure the VPN server, read the [OpenVPN guide](./6-open-vpn.md).
```

2023-10-03 20:57 UTC, jdpinedac commented on source/docs/casper/operators/aws-nodes/6-open-vpn.md
> +    $ bash
Indeed, it is accurate and has been verified. While this shift may appear radical, it is particularly within the procedure that change is evident: there is no longer a need to use SSH. Instead, simply executing bash will automatically present the license and initiate the entire initial configuration process for OpenVPN.

2023-10-04 09:31 UTC, ipopescu commented on source/docs/casper/operators/aws-nodes/6-open-vpn.md
> +    $ bash
Great, thanks for clarifying @jdpinedac!

2023-10-05 10:31 UTC, ipopescu commented
@jdpinedac please let me know when you are ready for another review. Thanks!

2023-10-12 22:55 UTC, jdpinedac commented on source/docs/casper/operators/aws-nodes/7-troubleshooting.md
> +    ```
Thank you for the observation.

2023-10-13 15:16 UTC, jdpinedac commented
Hello @ipopescu,

I have reviewed and implemented the relevant suggestions you provided. I've also updated the screenshots that required better resolution. I encountered a peculiar issue: some of the suggestions are not visible in the PR conversation on GitHub, but they were visible using the GitHub Pull Requests extension in VSCode. I hope I didn’t overlook anything. Please let me know if I missed something or if anything is wrong.
Thank you so much!

2023-10-16 11:14 UTC, ipopescu approved these changes
Updates look great! Thank you, @jdpinedac! I will merge them to the `1259_aws_nodes`. 

FYI, @devendran-m, the documentation is ready to go. We can merge the `1259_aws_nodes` branch to `dev` when the [repository](https://github.com/casper-ecosystem/casper-node-on-cloud/) goes public.
Also, a reminder to remove the wiki content from the repository, because it is obsolete now.

2023-10-16 11:14 UTC, merged

2023-10-16 15:42 UTC, ipopescu commented
Updated the branch name to protect it: [feat-aws_nodes](https://github.com/casper-network/docs/tree/feat-aws_nodes).