Clarification regarding token transfers
casper-network/docs pull request #1356
Opened 2024-01-22 12:41 UTC by ipopescu

### What does this PR fix/introduce?

As requested in [this thread](https://casper-labs-team.slack.com/archives/C01J86T699U/p1705923063189069?thread_ts=1705837279.975239&cid=C01J86T699U), I added a note clarifying that token transfers must be handled via stored contract (not stored session).

### Checklist

- [x] Docs are successfully building - `yarn install && yarn run build`.

### Reviewers
@ACStoneCL

2024-01-22 14:16 UTC, davidatwhiletrue requested changes

2024-01-22 14:16 UTC, davidatwhiletrue commented on source/docs/casper/resources/advanced/transfer-token-to-contract.md
> +For increased security, token transfers must be handled via contract code, not session code. As a result, `transfer-*` methods are unavailable in stored session code, even when the stored session run
@ipopescu the restriction applies only to transfers from the main purse in the account, not all transfers. On the other hand, it's the opposite way. "token transfers must be handled via session code, not contract code".

2024-01-22 21:06 UTC, ipopescu commented on source/docs/casper/resources/advanced/transfer-token-to-contract.md
> +For increased security, token transfers must be handled via contract code, not session code. As a result, `transfer-*` methods are unavailable in stored session code, even when the stored session run
Added this clarification with commit [1e77910](https://github.com/casper-network/docs/pull/1356/commits/1e77910ff00f506fe1449b0bcd9e32658ffede02). Please take a look, @davidatwhiletrue.

2024-01-23 09:26 UTC, davidatwhiletrue commented on source/docs/casper/resources/advanced/transfer-token-to-contract.md
> +For increased security, token transfers from a main purse must be handled via contract code, not session code as in [other cases](../../developers/writing-onchain-code/writing-session-code.md#example
@ipopescu  "handled via session code, not contract code", right?

For increased security, token transfers from an account main purse must be handled via **session code** as in [other cases](../../developers/writing-onchain-code/writing-session-code.md#example-3-transfers-using-session-code-transfers-using-session-code). Therefore, `transfer-*` methods are unavailable for tokens originated from an account main purse in stored session code, even when the stored session runs in the account context.

2024-01-24 01:07 UTC, Jiuhong-casperlabs commented on source/docs/casper/resources/advanced/transfer-token-to-contract.md
> +For increased security, token transfers from a main purse must be handled via contract code, not session code as in [other cases](../../developers/writing-onchain-code/writing-session-code.md#example
I would change a little
> token transfers from a main purse must be handled via contract code
=>

token transfers from a main purse must be handled via WASM code

2024-01-24 15:10 UTC, ipopescu commented on source/docs/casper/resources/advanced/transfer-token-to-contract.md
> +For increased security, token transfers from a main purse must be handled via contract code, not session code as in [other cases](../../developers/writing-onchain-code/writing-session-code.md#example
I've changed the wording with commit 76bd4e3. We don't have stored sessions anymore. What do you think?

2024-01-24 17:25 UTC, davidatwhiletrue commented on source/docs/casper/resources/advanced/transfer-token-to-contract.md
> +For increased security, token transfers from a main purse must be handled via contract code, not session code as in [other cases](../../developers/writing-onchain-code/writing-session-code.md#example
Looks good to me. Thanks @ipopescu

2024-01-24 17:25 UTC, davidatwhiletrue approved these changes

2024-01-26 18:53 UTC, ipopescu commented
I will merge this to close off the week. If there is any further feedback, I can always open another PR.

2024-01-26 18:53 UTC, merged