Update install-node.md
casper-network/docs pull request #1371
Opened 2024-02-13 08:08 UTC by adrpan

update libssl to actual link and some outputs due very outdated...

2024-02-13 15:11 UTC, ipopescu requested changes
Great updates. I've requested some changes though.

2024-02-13 15:11 UTC, ipopescu commented on source/docs/casper/operators/setup/install-node.md
> +https://packages.ubuntu.com/focal/amd64/libssl1.1/download
Please remove the standalone link; it's a bit confusing.
```suggestion
This message is due to the default `openssl` moving to 3.* with Ubuntu 22.04. You need to install [OpenSSL 1.*](https://packages.ubuntu.com/focal/amd64/libssl1.1/download) for prior versions of Ubuntu to use the Casper binaries with the following command:
```

2024-02-13 15:11 UTC, ipopescu commented on source/docs/casper/operators/setup/install-node.md
> +sudo dpkg -i ./libssl1.1_1.1.1f-1ubuntu2.21_amd64.deb
I suggest keeping the previous commands, unless you can explain why we should change them.
```suggestion
curl -f -JLO http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.21_amd64.deb
sudo apt install ./libssl1.1_1.1.1f-1ubuntu2.21_amd64.deb
```

2024-02-13 15:23 UTC, ACStoneCL commented
Your build is failing due to an external link problem from our end - if you update your branch, it should solve the problem.

2024-02-13 23:13 UTC, adrpan commented on source/docs/casper/operators/setup/install-node.md
> +sudo dpkg -i ./libssl1.1_1.1.1f-1ubuntu2.21_amd64.deb
sure it can be. I prefer install single packages via dpkg instead apt

2024-04-03 10:28 UTC, ipopescu commented
@adrpan could you please update this PR so we can take it forward?

2024-06-13 16:21 UTC, ipopescu commented
Closing this PR as I don't feel comfortable merging it. The link provided doesn't exist. If the changes need to be made, please retest them and submit a new PR.

2024-06-13 16:21 UTC, closed without merging