1426 cleanup
casper-network/docs pull request #1434
Opened 2024-04-16 21:50 UTC by ipopescu

### What does this PR fix/introduce?

After introducing Zug and the new rewards scheme, we need to review and update other pages in the documentation. This PR builds on #1429, so it pulls files from that PR. To make it clear, these are the files that need to be reviewed in this PR:

- source/docs/casper/concepts/about.md
- source/docs/casper/concepts/design/casper-design.md
- source/docs/casper/concepts/design/networking-protocol.md
- source/docs/casper/concepts/economics/consensus.md
- source/docs/casper/concepts/economics/index.md
- source/docs/casper/concepts/economics/runtime.md
- source/docs/casper/concepts/economics/staking/concepts.md
- source/docs/casper/concepts/economics/staking/delegation.md
- source/docs/casper/concepts/economics/staking/staking.md
- source/docs/casper/concepts/glossary/B.md
- source/docs/casper/concepts/glossary/C.md
- source/docs/casper/concepts/glossary/E.md
- source/docs/casper/concepts/glossary/P.md
- source/docs/casper/concepts/glossary/V.md
- source/docs/casper/concepts/glossary/Z.md
- source/docs/casper/concepts/intro-to-dapps.md
- source/docs/casper/operators/setup-network/chain-spec.md

Closes #1426.

### Checklist

- [x] Docs are successfully building - `yarn install && yarn run build`.
- [x] My changes follow the [Casper docs style guidelines](https://docs.casper.network/resources/contribute-to-docs/).

2024-04-17 20:58 UTC, AlexanderLimonov requested changes
Some relatively small changes are needed I think, but there's also further work on other aspects of 2.0 economics that might need to go in a separate PR

2024-04-17 20:58 UTC, AlexanderLimonov commented on source/docs/casper/concepts/economics/consensus.md
Material below this needs to be reworded because the new consensus-independent rewards don't care about consensus performance directly

2024-04-17 20:58 UTC, AlexanderLimonov commented on source/docs/casper/concepts/economics/consensus.md
> +Validators receive rewards for proposing and finalizing blocks according to their performance. The concept of weight is crucial for understanding this distribution scheme:
Needs to be reworked in light of new rewards

2024-04-17 20:58 UTC, AlexanderLimonov commented on source/docs/casper/concepts/economics/consensus.md
> +Switch blocks are not visible to the issuance calculation (as this calculation is performed in the switch block itself for each era), and, consequently, no rewards are issued for switch blocks.
This is no longer true with the new rewards, since we allow for "lookback" into a previous era, thereby enabling us to reward switch blocks in full

2024-04-17 20:58 UTC, AlexanderLimonov commented on source/docs/casper/concepts/economics/consensus.md
> +<!--TODO remove this? It is too old
Consult with @fizyk20, but I believe slashing functionality still exists in principle and can be activated.

Note that founding validator token lockup is not relevant to the public blockchain as it exists, but I believe that functionality also remains in the codebase and can be potentially used in new deployments. Perhaps should be asked in stand-up to identify someone who worked with this more recently than I have, however.

2024-04-17 20:58 UTC, AlexanderLimonov commented on source/docs/casper/concepts/economics/index.md
> +<!--TODO I suggest we remove this paragraph since it is 4 years old.
Agreed

2024-04-17 20:58 UTC, AlexanderLimonov commented on source/docs/casper/concepts/economics/index.md
> +The consensus layer of the Casper Mainnet runs the [Zug](../design/zug.md) consensus protocol. The distinguishing characteristics of this protocol are its safety and liveness guarantees. Specifically
Liveness is only mathematically guaranteed over 2/3 active weight, and I believe the network may, as a piece of software and not a theoretical construct, stall altogether below this, but @fizyk20 would know better

2024-04-17 20:58 UTC, AlexanderLimonov commented on source/docs/casper/concepts/economics/index.md
> +_Evictions_ deactivate validators who fail to participate in an era, turning off their bid and suspending their participation until they signal readiness to resume participation by invoking a particu
We should actually use "deactivating" here, I think

2024-04-17 20:58 UTC, AlexanderLimonov commented on source/docs/casper/concepts/economics/index.md
> +The runtime layer encompasses the deployment and execution of smart contracts, session code, and other activities that perform computation on the global state. This suggests potential markets for fin
This needs to drop the reference to the CEP and ask me later to provide specific wording that reflects the new dynamic pricing system for "spot" gas (you may have heard references to this as "block vacancy")

2024-04-17 20:58 UTC, AlexanderLimonov commented on source/docs/casper/concepts/economics/index.md
> +We expect to continue to work on runtime resource markets, particularly gas futures ([CEP #17](https://github.com/casper-network/ceps/pull/17)).
Delete the "particularly gas futures" part and the link. We do, however, expect to continue to work on this...

2024-04-17 20:58 UTC, AlexanderLimonov commented on source/docs/casper/concepts/economics/index.md
> +_Validators_ again play a vital role in this layer since protocol operation includes the construction and validation of new blocks, which consist of deploys that change the global state, which the va
Change "deploys" to "transactions" here and probably everywhere, unless discussing support for 1.5+ legacy supported behaviors.

2024-04-17 20:58 UTC, AlexanderLimonov commented on source/docs/casper/concepts/economics/index.md
> +### Incentives (runtime layer) {#incentives-runtime-layer}
Probably deserves its own cleanup PR, but note that we are going to the fee elimination model as a default, and therefore gas/balance holds will need to be discussed, again, probably, in a separate PR @ipopescu

2024-04-17 20:58 UTC, AlexanderLimonov commented on source/docs/casper/concepts/economics/runtime.md
> +The economics of the runtime layer should incentivize efficient allocation of computational resources, primarily CPU time, to users. Pending state pruning implementation, disk space use is treated as
We will likely need to remove the bit about state pruning, since we will, in fact, now support state pruning. Similarly gas price/"conversion rate" will no longer be fixed to 1 mote per 1 unit of gas ("block vacancy" again)

2024-04-17 20:58 UTC, AlexanderLimonov commented on source/docs/casper/concepts/economics/runtime.md
> +The Zug and Highway protocols reach consensus on a block _before_ the block is executed, introducing a subtle difference from platforms like Ethereum. In addition, deploys sent to a Casper network ca
"deploys" -> "transactions"

2024-04-17 20:58 UTC, AlexanderLimonov commented on source/docs/casper/concepts/economics/runtime.md
> +We expect to refine the current gas cost table to reflect time use more closely, with updates introduced in future upgrades. We also anticipate that storage costs will be calculated separately from c
Turns out the answer is "no" for now, despite introduction of state pruning. May change in 2.0+

2024-04-17 20:58 UTC, AlexanderLimonov commented on source/docs/casper/concepts/economics/runtime.md
> +The gas price is currently fixed at 1 mote per 1 gas unit.
See remarks about "block vacancy" above

2024-04-17 20:58 UTC, AlexanderLimonov commented on source/docs/casper/concepts/economics/runtime.md
>  ### Fee allocation {#fee-allocation}
This entire section will need a rework

2024-04-17 20:58 UTC, AlexanderLimonov commented on source/docs/casper/concepts/economics/runtime.md
> +<!--TODO check these old CEPs. Should we still mention them?
Delete

2024-04-17 20:58 UTC, AlexanderLimonov commented on source/docs/casper/concepts/economics/staking/concepts.md
> +**Consensus mechanism:** The Casper Mainnet and Testnet use a Proof-of-Stake consensus mechanism called [Zug](../../design/zug.md). A private Casper network can choose between Zug and [Highway](../..
Note that the network need not be private, it could be another public instance but with different parameters

2024-04-17 20:58 UTC, AlexanderLimonov commented on source/docs/casper/concepts/economics/staking/concepts.md
> +**Unbonding:** To detach from the Casper Mainnet, it takes seven eras for both validators and delegators. Neither validators nor delegators receive rewards during the seven eras required for unbondin
They do not receive rewards for current activity, but can still be rewarded for past signatures due to lookback, check with @fizyk20

2024-04-17 20:58 UTC, AlexanderLimonov commented on source/docs/casper/concepts/economics/staking/concepts.md
> +**Annual reward percentage:** Validators on the Casper Mainnet earned between 10% and 20% of their staked CSPR in the first year of the Mainnet operation, with regular participation under expected ne
We might want to update the numbers, ask MAKE (it's also possible Joe has the relevant data)

2024-04-17 20:58 UTC, AlexanderLimonov commented on source/docs/casper/concepts/economics/staking/concepts.md
> +**Block rewards:** Block time is orthogonal to [rewards](../../design/rewards.md), so there is no precise reward per block. Instead, the number of rewards is split proportionally among stakes and red
Might need a rework due to new rewards (promptness of consensus participation doesn't impact rewards directly)

2024-04-18 10:38 UTC, ipopescu commented on source/docs/casper/concepts/economics/runtime.md
> +<!--TODO check these old CEPs. Should we still mention them?
Done 1b80c7f4e2c4bdb5a3f545840ebd9a886940e0b2

2024-04-18 10:39 UTC, ipopescu commented on source/docs/casper/concepts/economics/staking/concepts.md
> +**Consensus mechanism:** The Casper Mainnet and Testnet use a Proof-of-Stake consensus mechanism called [Zug](../../design/zug.md). A private Casper network can choose between Zug and [Highway](../..
Done 1079ec41fea0c391c6171c76f649005036072544

2024-04-18 10:41 UTC, ipopescu commented on source/docs/casper/concepts/economics/index.md
> +<!--TODO I suggest we remove this paragraph since it is 4 years old.
Done 1b80c7f4e2c4bdb5a3f545840ebd9a886940e0b2

2024-04-18 10:46 UTC, ipopescu commented on source/docs/casper/concepts/economics/index.md
> +_Evictions_ deactivate validators who fail to participate in an era, turning off their bid and suspending their participation until they signal readiness to resume participation by invoking a particu
Done 1079ec41fea0c391c6171c76f649005036072544

2024-04-18 10:46 UTC, ipopescu commented on source/docs/casper/concepts/economics/index.md
> +We expect to continue to work on runtime resource markets, particularly gas futures ([CEP #17](https://github.com/casper-network/ceps/pull/17)).
Done 1079ec41fea0c391c6171c76f649005036072544

2024-04-23 11:29 UTC, ipopescu commented on source/docs/casper/concepts/economics/runtime.md
> +The Zug and Highway protocols reach consensus on a block _before_ the block is executed, introducing a subtle difference from platforms like Ethereum. In addition, deploys sent to a Casper network ca
I will address this in a [new PR](https://github.com/casper-network/docs/issues/1436), so I'll resolve this comment for now.

2024-04-23 11:30 UTC, ipopescu commented on source/docs/casper/concepts/economics/index.md
> +_Validators_ again play a vital role in this layer since protocol operation includes the construction and validation of new blocks, which consist of deploys that change the global state, which the va
I'll resolve this in a [new PR](https://github.com/casper-network/docs/issues/1436), so I'll close this comment.

2024-04-23 11:34 UTC, ipopescu commented on source/docs/casper/concepts/economics/index.md
> +### Incentives (runtime layer) {#incentives-runtime-layer}
Opened task https://github.com/casper-network/docs/issues/1437.

2024-05-01 16:02 UTC, ipopescu commented on source/docs/casper/concepts/economics/consensus.md
Reworded with a02f53a1ad35309874fdd00afc499f65d486050f. Please take a look.

2024-05-01 16:02 UTC, ipopescu commented on source/docs/casper/concepts/economics/consensus.md
> +Validators receive rewards for proposing and finalizing blocks according to their performance. The concept of weight is crucial for understanding this distribution scheme:
Updated with a02f53a1ad35309874fdd00afc499f65d486050f.

2024-05-01 16:05 UTC, ipopescu commented on source/docs/casper/concepts/economics/consensus.md
> +<!--TODO remove this? It is too old
I really think we need to clean this up and discuss only supported features. If we enable slashing, we need to discuss it in several places. As for the token unlocking, it is not applicable anymore as well.
I'll follow up with BK though, as suggested.

2024-05-01 16:09 UTC, ipopescu commented on source/docs/casper/concepts/economics/index.md
> +The consensus layer of the Casper Mainnet runs the [Zug](../design/zug.md) consensus protocol. The distinguishing characteristics of this protocol are its safety and liveness guarantees. Specifically
This is correct. Updated with commit 42e41951b127855fd8b304df5bc13ecd57c0c688 to say "The safety and liveness guarantees require that honest validators comprise at least 67% of total validator weight."

2024-05-01 16:11 UTC, ipopescu commented on source/docs/casper/concepts/economics/index.md
> +The runtime layer encompasses the deployment and execution of smart contracts, session code, and other activities that perform computation on the global state. This suggests potential markets for fin
Updated with commit 42e41951b127855fd8b304df5bc13ecd57c0c688. Once the page explaining "block vacancy" is ready, we can add a link.

2024-05-01 16:13 UTC, ipopescu commented on source/docs/casper/concepts/economics/runtime.md
> +The economics of the runtime layer should incentivize efficient allocation of computational resources, primarily CPU time, to users. Pending state pruning implementation, disk space use is treated as
Updated with commit a2e2b8852e5e3d82a9d2a8a6f89a7d56a37abb7a.

2024-05-01 16:13 UTC, ipopescu commented on source/docs/casper/concepts/economics/runtime.md
> +We expect to refine the current gas cost table to reflect time use more closely, with updates introduced in future upgrades. We also anticipate that storage costs will be calculated separately from c
Updated with commit a2e2b8852e5e3d82a9d2a8a6f89a7d56a37abb7a.

2024-05-01 16:14 UTC, ipopescu commented on source/docs/casper/concepts/economics/runtime.md
> +The gas price is currently fixed at 1 mote per 1 gas unit.
Updated with a2e2b8852e5e3d82a9d2a8a6f89a7d56a37abb7a. We need to link to the new page explaining gas here.

2024-05-01 16:15 UTC, ipopescu commented on source/docs/casper/concepts/economics/runtime.md
>  ### Fee allocation {#fee-allocation}
Updated with https://github.com/casper-network/docs/commit/a2e2b8852e5e3d82a9d2a8a6f89a7d56a37abb7a. We need to link to the new page explaining gas here.

2024-05-01 16:17 UTC, ipopescu commented on source/docs/casper/concepts/economics/staking/concepts.md
> +**Unbonding:** To detach from the Casper Mainnet, it takes seven eras for both validators and delegators. Neither validators nor delegators receive rewards during the seven eras required for unbondin
Updated with commit a2e2b8852e5e3d82a9d2a8a6f89a7d56a37abb7a.

2024-05-01 16:21 UTC, ipopescu commented on source/docs/casper/concepts/economics/staking/concepts.md
> +**Block rewards:** Block time is orthogonal to [rewards](../../design/rewards.md), so there is no precise reward per block. Instead, the number of rewards is split proportionally among stakes and red
Updated with commit a2e2b8852e5e3d82a9d2a8a6f89a7d56a37abb7a.

2024-05-01 16:29 UTC, ipopescu commented
@AlexanderLimonov I have addressed as many comments as possible. New content explaining incentives, gas, and fees should be added or linked using a new PR -- unless it can be done quickly at a summary level.
I am following up on 3 comments:
- [r1569509946](https://github.com/casper-network/docs/pull/1434#discussion_r1569509946)
- [r1569536010](https://github.com/casper-network/docs/pull/1434#discussion_r1569536010)
- [r1569537495](https://github.com/casper-network/docs/pull/1434#discussion_r1569537495)

2024-05-01 16:57 UTC, ipopescu commented on source/docs/casper/concepts/economics/staking/concepts.md
> +**Annual reward percentage:** Validators on the Casper Mainnet earned between 10% and 20% of their staked CSPR in the first year of the Mainnet operation, with regular participation under expected ne
From a discussion with Joe: 

For delegators, it would depend on the validator they use. According to the display on cspr.live, 10-20 is accurate. 10-14 is safely more accurate, minus the validator fee.
We would need to look at the staked amount vs the total supply to have that exact.

I think we should clarify if we are talking about validator rewards or delegator rewards. Or both?

2024-05-01 17:00 UTC, ipopescu commented on source/docs/casper/concepts/about.md
> +The network's consensus protocol is called [Zug](./design/zug.md), and it has several benefits over classic Byzantine Fault Tolerant (BFT) consensus protocols. First, Zug allows networks to reach hig
@ACStoneCL we need to merge this change [with your PR](https://github.com/casper-network/docs/pull/1439/files).

2024-05-01 17:12 UTC, ipopescu commented on source/docs/casper/concepts/design/casper-design.md
> +Casper is a decentralized Proof-of-Stake blockchain platform that uses a consensus algorithm called [Zug](./zug.md). Having a unit of value is required to make this system work because users must pay
Merge required with PR 1439:
Casper is a decentralized Proof-of-Stake blockchain platform that may use either the [Highway](./highway.md) or [Zug](./zug.md) consensus mechanisms..

2024-05-02 10:41 UTC, ipopescu commented on source/docs/casper/concepts/economics/consensus.md
> +<!--TODO remove this? It is too old
I got feedback from BK. He agrees to remove the point about slashing for now but keep the point about the unlocking period.
Updated with commit 8ca79bef23167fdb632b0fe228adda2f897b81d3.

2024-05-02 10:43 UTC, ipopescu commented on source/docs/casper/concepts/economics/staking/concepts.md
> +**Unbonding:** To detach from the Casper Mainnet, it takes seven eras for both validators and delegators. Neither validators nor delegators receive rewards during the seven eras required for unbondin
Confirmed with BK that the wording used in a2e2b8852e5e3d82a9d2a8a6f89a7d56a37abb7a for unbonding  is correct.

2024-05-02 10:44 UTC, ipopescu commented on source/docs/casper/concepts/economics/staking/concepts.md
> +**Annual reward percentage:** Validators on the Casper Mainnet earned between 10% and 20% of their staked CSPR in the first year of the Mainnet operation, with regular participation under expected ne
Currently cspr.live shows  12.11%.

2024-05-02 10:51 UTC, ipopescu commented
Resolved 2/3 of the open comments:
- [r1569509946](https://github.com/casper-network/docs/pull/1434#discussion_r1569509946) => new commit [8ca79be](https://github.com/casper-network/docs/pull/1434/commits/8ca79bef23167fdb632b0fe228adda2f897b81d3)
- [r1569536010](https://github.com/casper-network/docs/pull/1434#discussion_r1569536010) => OK as it was
- [r1569537495](https://github.com/casper-network/docs/pull/1434#discussion_r1569537495) => added details from Joe in the comment.

2024-05-02 21:10 UTC, AlexanderLimonov commented on source/docs/casper/concepts/economics/staking/concepts.md
> +**Annual reward percentage:** Validators on the Casper Mainnet earned between 10% and 20% of their staked CSPR in the first year of the Mainnet operation, with regular participation under expected ne
It's fine for now, since this whole section needs a refresh

2024-05-02 21:10 UTC, AlexanderLimonov approved these changes

2024-05-03 12:01 UTC, ACStoneCL approved these changes
LGTM!

2024-05-03 13:27 UTC, merged