Major rework of public-facing economic documentation
casper-network/docs pull request #154
Opened 2021-03-31 02:12 UTC by AlexanderLimonov

2021-03-31 10:19 UTC, afck approved these changes
Looks good to me! :+1: 
Just a few nit-picks.
(And we should probably wait for a few more approvals before merging.)

2021-03-31 10:19 UTC, afck commented on economics/runtime.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^
```suggestion
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

2021-03-31 10:19 UTC, afck commented on economics/runtime.rst
> +The Highway protocol in its mainnet implementation reaches consensus on a block *before* the block is executed. This introduces a subtle difference from platforms like Ethereum. Deploys sent to the C
`only be selected only` → `be selected only`

2021-03-31 10:19 UTC, afck commented on economics/runtime.rst
> +The Highway protocol in its mainnet implementation reaches consensus on a block *before* the block is executed. This introduces a subtle difference from platforms like Ethereum. Deploys sent to the C
Probably "Network" should be uppercase in "the Casper Network"? (Not sure whether it's considered part of the proper name.)

2021-03-31 10:19 UTC, afck commented on economics/runtime.rst
> +It is expected that the current gas cost table will be refined over time to reflect time use more closely, with updates introduces in future upgrades. It is also anticipated that, with the introducti
`updates introduces` → `updates introduced`?

2021-03-31 10:19 UTC, afck commented on economics/runtime.rst
> +Block gas limit is split into two lanes, one for native transfers and one for general deploys.
Is it the _gas_ or the _number_ of deploys, in the current implementation?

2021-03-31 10:19 UTC, afck commented on economics/runtime.rst
> +All fees from a particular block accrue to its proposed. This incentivizes block production and allows major dApps to execute their own deploys for free, provided they operate a validator node and ar
`its proposed` → `its proposer`

2021-04-17 11:30 UTC, MParlikar requested changes

2021-04-17 11:30 UTC, MParlikar commented on economics/consensus.rst
> +Validators who send no messages during the era are marked as inactive and cease to participate in the auction until sending a special deploy that reactivates their bid.
'an entire era'

2021-04-17 11:30 UTC, MParlikar commented on economics/consensus.rst
> +Founding validators are subject to token lock-up, which prevents them from withdrawing any tokens from their bids for 90 days, then releases their genesis bid tokens in weekly steps, linearly, over t
tokens are locked for  90 days from genesis, and then release over another 90 days - not 180.

2021-04-17 11:30 UTC, MParlikar commented on economics/economicsoverview.rst
> +*Number of validators:* The Casper Delta testnet supports up to 100 validators on the network. This number is chosen to strike a balance between performance and decentralization. This platform parame
mainnet is also at 100

2021-04-19 02:14 UTC, AlexanderLimonov commented on economics/consensus.rst
> +Participation is incentivized by scaling rewards for on-time proposals and responses, taking into account the speed of finalization. All rewards are added directly to the corresponding bids and deleg
The docs overall make it pretty clear that there are transaction fees, but here I'm talking only about the consensus layer.

2021-04-19 02:19 UTC, AlexanderLimonov commented on economics/consensus.rst
> +   supply(i) = initial_supply * (1 + issuance_rate)^(i / ticks_per_year)
This was used, nominally, as the spec. The particular formula should say tick_at_era_start(i) instead of just i though. The complication Andreas describes appears a few lines after this.

2021-04-19 02:30 UTC, AlexanderLimonov commented on economics/consensus.rst
> +We dictate a minimum assigned weight for all rounds. Rounds that meet the requirement are said to be *feasible*, and the ones that do not are said to be *infeasible*. Blocks proposed in infeasible ro
Part of the problem here is that I was trying to minimally change a document that was the de facto spec, which I still need to essentially re-write, while keeping track of what changed in implementation

2021-04-19 02:33 UTC, AlexanderLimonov commented on economics/consensus.rst
> +We dictate a minimum assigned weight for all rounds. Rounds that meet the requirement are said to be *feasible*, and the ones that do not are said to be *infeasible*. Blocks proposed in infeasible ro
Also, reduced block rewards are described a couple of lines later.

2021-04-19 02:35 UTC, AlexanderLimonov commented on economics/economicsoverview.rst
> +*Number of validators:* The Casper Delta testnet supports up to 100 validators on the network. This number is chosen to strike a balance between performance and decentralization. This platform parame
Sorry, I didn't notice that it said "testnet" in a couple of places."

2021-05-06 05:13 UTC, MParlikar requested changes

2021-05-10 17:25 UTC, AlexanderLimonov commented on economics/economicsoverview.rst
> +Casper staking crib sheet
A cheat sheet! I'll revert it.

2021-05-11 23:25 UTC, AlexanderLimonov commented on economics/index.rst
>  *Validators* are responsible for maintaining platform security by building an ever-growing chain of finalized blocks, backing this chain's security with their stakes. Their importance (often referred
Removing the operator section - we _do_ have an accepted CEP on this, https://github.com/casper-network/ceps/blob/master/text/0031-designated-operators.md, but it was never implemented (given the instances of self-delegation, I suppose it's a candidate for reversion).

2021-05-31 20:05 UTC, ipopescu approved these changes
@AlexanderLimonov please give this PR a final look. I made a few changes to simplify the explanations, yet retain their meaning. I also went through all the feedback and addressed some additional minor requests.
@MParlikar we need your approval to unblock the PR, due to the requested changes. 

Summary of updates:
- Broader changes in flow to simplify the language on the consensus page (commit fac4fca41ae13f88641f82d941be340679aee616)
- Changed “Overview of economics” back to “Economics” to follow convention in the top menu. Instead, I added one sentence to explain that the page is an overview (commit b31b2a3984c54e37a1e75c6f47921c16f705e75e)
- Very minor updates to the index page (commit 054e557f479276488f6e9285ca9513a4016b9c8f)
- Minor updates to the runtime page (commit 054e557f479276488f6e9285ca9513a4016b9c8f)
- Since there is already a [staking guide](https://docs.casperlabs.io/en/latest/staking/index.html), I think we should rename the “Casper Staking Guide” page to “Staking Concepts”. Also, I’ve removed block processing time for testnet from the docs (it was referring to Delta). (commit 7c980a503ed40dcb93d99787dd96614d41a578d9)
- I also renamed the file from “economicsoverview” to “stakingconcepts” (commit 7c980a503ed40dcb93d99787dd96614d41a578d9)
- Updated  page titles to use capital letters (commit 7c980a503ed40dcb93d99787dd96614d41a578d9)
- Archived the “issuance” file to make sure it isn’t included by mistake in the future (commit …)

2021-05-31 20:08 UTC, ipopescu commented on economics/consensus.rst
> +Several eras after genesis, the system settles into selecting a set of validators several eras in advance, governed by the *auction_delay* chainspec parameter. This is done by means of a stake auctio
Addressed this by simplifying the paragraph.

2021-05-31 20:19 UTC, ipopescu commented on economics/consensus.rst
> +- The growth of CSPR supply is exponential instead of linear
Changed to "This is analogous to block rewards in Proof-of-Work blockchains, outlining the following:"

2021-05-31 20:25 UTC, ipopescu commented on economics/economicsoverview.rst
> +Casper staking crib sheet
I think this should be called "staking concepts", because we already have a [staking guide](https://docs.casperlabs.io/en/latest/staking/index.html). Addressed with commit 7c980a503ed40dcb93d99787dd96614d41a578d9.

2021-05-31 20:26 UTC, ipopescu commented on economics/economicsoverview.rst
> +*Eras and block times:* An era on Casper is roughly 2 hours long. The block time on today's testnet is approximately two minutes. Casper's Highway protocol allows validators to propose blocks as quic
Since we don't own testnet anymore, let's not include it in this document.

2021-05-31 20:29 UTC, ipopescu commented on economics/consensus.rst
> +   supply(i) = initial_supply * (1 + issuance_rate)^(i / ticks_per_year)
Does this line need to be updated, or can we close the conversation and the PR?

2021-05-31 20:30 UTC, ipopescu commented on economics/consensus.rst
> +We dictate a minimum assigned weight for all rounds. Rounds that meet the requirement are said to be *feasible*, and the ones that do not are said to be *infeasible*. Blocks proposed in infeasible ro
Can we close this discussion?

2021-06-05 00:48 UTC, AlexanderLimonov commented on economics/consensus.rst
> +Once a block has been proposed and enough time has passed, the message log can be examined to detect whether the block was finalized on time, according to the conditions given above. If the block was
Note that I'm referring here to the internal representation used by consensus, not an externally visible log. Maybe "consensus DAG" instead?

2021-06-05 00:50 UTC, AlexanderLimonov commented on economics/runtime.rst
> +The economics of the runtime layer intend to incentivize efficient allocation of computational resources, primarily CPU time, to users. Pending state pruning implementation, disk space use is treated
Maybe we should just say "should" instead of "intend to?"

2021-06-05 00:53 UTC, AlexanderLimonov commented on economics/runtime.rst
> +The block gas limit is split into two lanes, one for native transfers and one for general deploys. The number of transfers, which cost a fixed amount of gas, is governed directly by the ``block_max_t
This should not say "motes" - the hard cap is on # of transfers themselves

2021-06-07 13:57 UTC, ipopescu commented on economics/consensus.rst
> +Once a block has been proposed and enough time has passed, the message log can be examined to detect whether the block was finalized on time, according to the conditions given above. If the block was
In this case, I propose we replace "the message log" with "a common history of protocol messages". Otherwise, we can talk about the consensus DAG, but we need to explain what the DAG is: "nodes jointly maintain a common history of protocol messages, forming a directed acyclic graph representing the causality order". I propose we go with the simpler version in commit 167b1c65202c290e407ec3a1dcd68ff8b7c76fe9.

2021-06-07 14:05 UTC, ipopescu commented on economics/runtime.rst
> +The block gas limit is split into two lanes, one for native transfers and one for general deploys. The number of transfers, which cost a fixed amount of gas, is governed directly by the ``block_max_t
Removed motes in commit d3ef94d4f3d11b2181e56ca110a958397ce6b0af and I checked the production chainspec: https://github.com/casper-network/casper-node/blob/d35ae61c22f11b8c4df0852a63b7cca7d81b4ba3/resources/production/chainspec.toml.

2021-06-07 14:06 UTC, ipopescu commented on economics/runtime.rst
> +The economics of the runtime layer intend to incentivize efficient allocation of computational resources, primarily CPU time, to users. Pending state pruning implementation, disk space use is treated
Addressed in commit d3ef94d4f3d11b2181e56ca110a958397ce6b0af.

2021-06-08 18:22 UTC, ipopescu commented on economics/consensus.rst
> +Once a block has been proposed and enough time has passed, the message log can be examined to detect whether the block was finalized on time, according to the conditions given above. If the block was
After further discussing this with Alexander, I removed the word "common" to avoid ambiguity. We will say: "Once a block has been proposed and enough time has passed, the history of protocol messages can be examined to detect whether the block was finalized on time".

2021-06-08 18:34 UTC, afck commented on economics/consensus.rst
> +We dictate a minimum assigned weight for all rounds. Rounds that meet the requirement are said to be *feasible*, and the ones that do not are said to be *infeasible*. Blocks proposed in infeasible ro
That sounds good, thanks!

2021-06-09 05:04 UTC, merged