Update ERC20 tutorial -implementation section
casper-network/docs pull request #158
Opened 2021-12-22 11:05 UTC by Buddhika-Pathirathna

Please verify the new content

2021-12-22 15:57 UTC, dylanireland commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/implementation.md
> +To see the full implementation of below contract methods, refer the [contract file](https://github.com/casper-ecosystem/erc20/blob/master/example/erc20-token/src/main.rs) in Github. If you have any q
refer to the contract file sounds a bit cleaner than "refer the contract file"

2021-12-22 15:58 UTC, dylanireland commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/implementation.md
> +Initializing the contract happens through the `call()` function inside the [contract file](https://github.com/casper-ecosystem/erc20/blob/master/example/erc20-token/src/main.rs). When you deploy the
I think 'which are the starting token supply' sounds a bit clunky.

2021-12-22 16:02 UTC, dylanireland commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/implementation.md
> +The code snippet is something like below for initializing the contract,
"The code snippet for initializing the contract should look like this:"

2021-12-22 16:03 UTC, dylanireland requested changes
Great work, I added a few comments regarding some minor grammatical updates. Then looks like we can merge.

2021-12-22 16:27 UTC, Buddhika-Pathirathna commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/implementation.md
> +Initializing the contract happens through the `call()` function inside the [contract file](https://github.com/casper-ecosystem/erc20/blob/master/example/erc20-token/src/main.rs). When you deploy the
> 

Thanks a lot for reviewing and adding the comments, I will check do the changes and commit again

2021-12-24 11:25 UTC, deuszex commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/implementation.md
> +<img src={useBaseUrl("/image/tutorials/erc-20/erc20-implementation-install-crates.png")} alt="import-crates" width="800"/>
Why would you want to include a picture instead of the embedded code?

2021-12-24 11:44 UTC, deuszex requested changes

2021-12-24 11:44 UTC, deuszex commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/implementation.md
> + Please note that in order to execute the complete contract you need to copy the full contract file with all the necessary imports, declarations, and functions.
This needs clarifications.

To execute the contract you need to deploy the .wasm

To compile the reference contract with all provided functionalities, you need the stated parts.

2021-12-24 11:44 UTC, deuszex commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/implementation.md
> +To see the full implementation of the below contract methods, refer to the [contract file](https://github.com/casper-ecosystem/erc20/blob/master/example/erc20-token/src/main.rs) in Github. If you hav
The last two links they should look up for more details. If they still have questions they should reach out to us preferably on the discord channel.

2021-12-24 11:44 UTC, deuszex commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/implementation.md
> +To see the full implementation of the below contract methods, refer to the [contract file](https://github.com/casper-ecosystem/erc20/blob/master/example/erc20-token/src/main.rs) in Github. If you hav
Should also consider that there are not just methods but `entry_points` to be specific.

2021-12-24 16:45 UTC, Buddhika-Pathirathna commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/implementation.md
> +<img src={useBaseUrl("/image/tutorials/erc-20/erc20-implementation-install-crates.png")} alt="import-crates" width="800"/>
To better clarity and avoid partial copy-paste by users.

2021-12-27 13:34 UTC, deuszex approved these changes

2021-12-27 15:32 UTC, dylanireland approved these changes

2021-12-27 15:35 UTC, merged

2021-12-28 02:13 UTC, ipopescu reviewed
Reviewing retroactively. Nice work, @Buddhika-Pathirathna! Thank you!

2021-12-28 02:13 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/implementation.md
> +<img src={useBaseUrl("/image/tutorials/erc-20/erc20-implementation-install-crates.png")} alt="import-crates" width="800"/>
Good idea @Buddhika-Pathirathna. We had several users copying and pasting only the call function, resulting in wasted support conversations.