Adding erc20 deploy contract page
casper-network/docs pull request #173
Opened 2022-01-07 16:20 UTC by Buddhika-Pathirathna

Initial changes

2022-01-10 12:41 UTC, deuszex requested changes

2022-01-10 12:41 UTC, deuszex commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +- Account should contain enough `CASPR tokens` to proceed with the deploy. These will use to pay for the transactions on the Casper Network (involving ERC-20 tokens).
CSPR

2022-01-10 19:59 UTC, ipopescu requested changes
@Buddhika-Pathirathna thank you, the content is very good. A few requests before merging:
- Please check the style guide, reword and simplify the writing. I left some suggestions.
- Please mention the faucet somewhere, for people to request tokens.
- I am not sure if this section is needed "Sample Deploy on Testnet", but if you want to keep it, make sure it does not contain any sensitive information. Also, outside of this section, all the paths and arguments should be generic.

Great work! Let me know if you have any questions :).

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +Now that you have implemented the smart contract for ERC20 and it's time to deploy. Deploying the ERC20 contract is similar to deploying other smart contracts, while only the WASM files and parameter
Use ERC-20 instead of ERC20 in all places.

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +Now that you have implemented the smart contract for ERC20 and it's time to deploy. Deploying the ERC20 contract is similar to deploying other smart contracts, while only the WASM files and parameter
Suggestion to apply these edits:
"Now that you have implemented the smart contract for ERC-20, it's time to deploy it to the blockchain. Deploying the ERC-20 contract is similar to deploying other smart contracts, while only the WASM files and parameters will differ. Refer to the [Deploying Contracts](/docs/dapp-dev-guide/deploying-contracts#advanced-deployments) section to learn more about overall contract deployment."

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +- You need to have a pre-created `Casper Signer Account` with the required amount of tokens to perform the deploy
Point to the Signer guide: https://casper.network/docs/workflow/signer-guide

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +- Account should contain enough `CASPR tokens` to proceed with the deploy. These will use to pay for the transactions on the Casper Network (involving ERC-20 tokens).
Remove "." at the end

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +- Generated `Public Key` and `Private Key` to perform the deploy and related actions
What about moving this with the Signer account point?

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +- Installed [casper client](/dapp-dev-guide/tutorials/counter/setup) to interact with the network
Let's capitalize Casper

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +
Capitalize Network. Also, you can say: "Here are the basic steps to deploy the ERC-20 contract on the Casper Network."

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +<img src={useBaseUrl("/image/tutorials/erc-20/erc20-deply-flow.png")} alt="erc20-deploy-flow" width="500"/>
Add ERC-20 in the image. Also, you could say, "Query Contract" instead.

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +1. Clone the contract from the repo
I'd say "repository" or GitHub and add a link to it.

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +3. Builds and verifies the compiled contract
Say "Build and verify" to match the other points.

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +:::
Please simplify this as such:
"[Acquire a node address](/docs/workflow/setup#acquire-node-address-from-network-peers) from the Testnet and use port '7777' instead of '35000' to send your deploy. If the selected peer is unresponsive, pick a different peer and try again."

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +<img src={useBaseUrl("/image/tutorials/erc-20/testnet-peers.png")} alt="erc20-deploy-flow" width="800"/>
Nice to have: it would be good to mask out the key in the top right, with a program such as Snagit or Skitch. Let me know if you have questions about this.

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +This query capture any information related to the state of the blockchain at the specific time denoted by state root hash. To view this, you need to have the state root hash and the account hash. Use
I would simplify:
"This query captures information related to the state of the blockchain at the specific time denoted by the state root hash. You need to have the state root hash and the account hash to run the query."

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +**Get State Root Hash**
"Getting the State Root Hash" (following the styling guide)

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +This marks a snapshot of the network state at a moment of time.
Use "moment in time"

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +**Get Account Hash**
Getting the Account Hash (following the styling guide)

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +casper-client account-address --public-key "/home/ubuntu/public_key_hex"
Use a generic path instead.

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +This is the identification of your account.
Re-write: "To get the account hash, run the following command and supply the path to your Public Key in Hex format."

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +**Query the Network State**
Use gerund according to the style guide: "Querying..."

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +Use the below command template to query the network status with regards to your account.
"Use the command template below"

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +- `<HOST:PORT>`: Use the [node-ip-address](../erc20/deploy#get-an-ip-address-from-a-testnet-peer) taken from a testnet peer.
Move this above, in the instructions on how to use the command. 
Capitalize Testnet. 
Say Node IP address rather than "node-ip-address".

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +**Query with Arguments**
Use gerund: Querying...

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +This contains the header, payment and session details along with the
Sentence not completed. What did you try to say here?

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +{
Add a section to collapse the result. The How To guides use this.

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +**View the deploy details**
Use gerund here

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +You can view the details of the applied deploy using below command:
"the command below"

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +--node-address http://95.216.24.237:7777 \
Use generic node addresses, otherwise people will just copy and paste.

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +The deploy command:
"Deploy the contract with this command:"

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +The deploy command:
I know this is an example, but I think all commands need to have generic paths, otherwise, people will copy and paste them without thinking about the details.

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +{
Collapse the result when it is very long. See https://casper.network/docs/workflow/querying#obtaining-the-global-state-root-hash.

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +This contains the network state before the deploy. You can see the `named-key` field is empty since we haven't done any deploy on the network yet.
"This **result** contains .."

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +--state-root-hash E5B679BD1562fE6257257F5f969A79482E8DCEBBD501501BfA6d5844b61cBE3f
Use generic values... I am not sure about adding such details in the docs.

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +The following steps will guide you through the series of above-described steps with actual values and results.
I am not sure about this, Buddhika. People will start copying and pasting.

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +--key account-hash-7f4bf39A311a7538d8C91BB86C71DF774023e16bc4a70ab7e4e8AE77DbF2Ef53 \
I would not include the account address.

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +The following steps will guide you through the series of above-described steps with actual values and results.
If you really want to keep this, then create your own values such as 9999999999....9999999.

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +The following steps will guide you through the series of above-described steps with actual values and results.
Re-write "guide you through the **process** with actual values and results".

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +Use below command template to query with arguments:
"Use the command template below to query the network state:"

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +- `PAYMENT_AMOUNT`: Gas amount in tokens send for the execution. If there are no adequate tokens, deploy will not execute and will return an error
You need to mention the faucet somewhere and point to this page: https://casper.network/docs/workflow/token-transfer#2-the-faucet.
Also re-write: "Gas amount in tokens needed for contract execution. If there are no adequate tokens, the deploy will not execute and return an error"

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +- `WASM FILE PATH`: The session-path argument should point to wherever you compiled erc20 WASM file on your machine
Re-write: "The session-path argument should point to the location of your compiled ERC-20 WASM file."

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +If you are performing the deploy in the mainnet, it's recommended to try several put deploys on the testnet or local machine to figure out the exact amount required for that deploy. Refer [note about
Re-write: "If you are performing the deploy on the Mainnet, we recommend trying several deploys on the Testnet to understand the exact amount required for the deploy. Refer to the [note about gas price](/docs/dapp-dev-guide/deploying-contracts#a-note-about-gas-prices) to understand more about payment amounts and gas price adjustments." Add a colon. Also, do not mention a local network, unless you want to specify that the local network needs to have the same configuration as the Mainnet (otherwise the gas price would be different).

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +## Query the Network Status
Use gerunds in the titles, according to the style guide.

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +Now you have deployed the contract to the network and the status of the network has changed. To view the network status you need to get the newest state root hash because it has changed with the depl
Simplify wording, remove the first sentence, and use: "You need to get the newest state root hash to view the network status because it has changed with the deploy. The account hash remains the same since you are using the same account. Follow [View network state](../erc20/deploy#view-the-network-status) to execute this step with the new state root hash."

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +Now we can verify the applied deploy using the `get deploy` command. This will output the details of the applied deploy.
Use "you" instead of "we".

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +We checked the query state at a global level in [previous query the network](../erc20/deploy#view-the-network-status) step. In this step, we will narrow down the context and check the status specific
Recommending to re-write this and removing the first sentence: 
"This step will narrow down the context and check the status of a specific entry point. You will use the details inside the [ERC-20 contract](https://github.com/casper-ecosystem/erc20/blob/master/example/erc20-token/src/main.rs) to derive arguments."

2022-01-10 19:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +We checked the query state at a global level in [previous query the network](../erc20/deploy#view-the-network-status) step. In this step, we will narrow down the context and check the status specific
What do you mean by "certain area"? Could you be more specific? Do you refer to entry points?

2022-01-11 15:58 UTC, Buddhika-Pathirathna commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +We checked the query state at a global level in [previous query the network](../erc20/deploy#view-the-network-status) step. In this step, we will narrow down the context and check the status specific
Yes, it should be entry point - Thanks Iulia

2022-01-11 16:13 UTC, Buddhika-Pathirathna commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +The following steps will guide you through the series of above-described steps with actual values and results.
> If you really want to keep this, then create your own values such as 9999999999....9999999.

I am not much bias on this point @ipopescu,  after your thoughts, I also felt like better to remove this part, shall we ask from @GloreenS , @darthsiroftardis, and @deuszex as well?

2022-01-11 17:41 UTC, darthsiroftardis requested changes
There are some changes I would like to see addressed before I can approve. Please reach out to me if there are any blockers in addressing these changes.

2022-01-11 17:41 UTC, darthsiroftardis commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +- You need to have a pre-created [Casper signer account](https://casper.network/docs/workflow/signer-guide) with the required amount of tokens to perform the deploy
This sentence implies that the account must be created with the Casper signer, when thats not really true. As long as they have an Account it would be fine. 

```suggestion
- You need to have a pre-created [Account](https://casper.network/docs/workflow/setup#setting-up-an-account) with the required amount of tokens to perform the deploy
```

2022-01-11 17:41 UTC, darthsiroftardis commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +  - You will receive the `Public Key` and `Private Key` along with the Casper signer account which are mandatory items for the future deploys
```suggestion
  - You will receive the `Public Key` and `Private Key` corresponding to the `Account` which are mandatory items for the future deploys
```

2022-01-11 17:41 UTC, darthsiroftardis commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +- `NETWORK_NAME`: Use the relevant network name. Here we use 'testnet'
```suggestion
- `NETWORK_NAME`: Use the relevant network name. Here we use 'casper-test'
```

Testnet's network name is `casper-test`

2022-01-11 17:41 UTC, darthsiroftardis commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +If you are performing the deploy in the Mainnet, we recommend trying several put deploys on the Testnet to understand the exact amount required for that deploy. Refer to the [note about gas price](/d
Please add a note, that we currently do not refund any tokens as part of a deploy. If the deployment costed say 1 CSPR but you sent the deploy with 10 CSPR, the system will not return the extra 9 CSPR

2022-01-11 17:41 UTC, darthsiroftardis commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +Now you can verify the applied deploy using the `get deploy` command. This will output the details of the applied deploy.
```suggestion
Now you can verify the applied deploy using the `get-deploy` command. This will output the details of the applied deploy.
```

2022-01-11 17:41 UTC, darthsiroftardis commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +    "execution_results": [
Please mention that if this field is represented as `"execution_results":[]` means that the deploy hasn't executed yet. Depending on the network, there will be some time before this field contains the results of the execution.

2022-01-11 17:41 UTC, darthsiroftardis commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +            "error_message": "Out of gas error",
Could we please provide an example of a successful deployment

2022-01-11 18:05 UTC, ipopescu commented
@Buddhika-Pathirathna, from the other review comments, the team finds useful the specific example you had, so please keep it :). You might want to double-check that there is no sensitive information to be shared in GitHub.

2022-01-12 05:54 UTC, Buddhika-Pathirathna commented
> There are some changes I would like to see addressed before I can approve. Please reach out to me if there are any blockers in addressing these changes.

Thanks a lot for your valuable input Karan, I will apply those and get back to you if find anything needs more details

2022-01-12 05:56 UTC, Buddhika-Pathirathna commented
> @Buddhika-Pathirathna thank you, the content is very good. A few requests before merging:
> 
> * Please check the style guide, reword and simplify the writing. I left some suggestions.
> * Please mention the faucet somewhere, for people to request tokens.
> * I am not sure if this section is needed "Sample Deploy on Testnet", but if you want to keep it, make sure it does not contain any sensitive information. Also, outside of this section, all the paths and arguments should be generic.
> 
> Great work! Let me know if you have any questions :).

Thanks a lot for taking the time to review this Iulia, I value every feedback and have adjusted those accordingly.

2022-01-12 09:19 UTC, Buddhika-Pathirathna commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +    "execution_results": [
@darthsiroftardis , please explain the second part of this sentence, is that mean different networks may take different times to load the execution result?

2022-01-12 13:03 UTC, ipopescu reviewed
@Buddhika-Pathirathna could you please run through my previous editing suggestions to make sure they are applied?

2022-01-12 17:45 UTC, ipopescu commented
Thanks for the updates, @Buddhika-Pathirathna. Is it possible to rename this png to “erc20-deploy-flow.png” and to update the content in the first box and second-last box to say:
- Clone the ERC-20 Contract
- Query Contract with Arguments

2022-01-12 18:56 UTC, ipopescu reviewed
@Buddhika-Pathirathna could you please review my suggestions from PR 182: https://github.com/casper-network/docs/pull/182.

2022-01-13 13:01 UTC, ipopescu approved these changes
Thank you, @Buddhika-Pathirathna .Great work!

2022-01-13 15:23 UTC, deuszex approved these changes

2022-01-13 15:28 UTC, darthsiroftardis reviewed
Some incorrect information, that should be corrected.

2022-01-13 15:28 UTC, darthsiroftardis commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +- Ensure you have a pre-created [Account](https://casper.network/docs/workflow/setup#setting-up-an-account) with the required amount of tokens to perform the deploy
```suggestion
- Ensure you have an [Account](https://casper.network/docs/workflow/setup#setting-up-an-account), the associated key pair,  and the required amount of tokens to perform the deploy
```

2022-01-13 15:28 UTC, darthsiroftardis commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +  - You will receive the *Public Key* and *Private Key* along with the Casper signer account. Those will use to query the network
This line can be removed

2022-01-13 15:28 UTC, darthsiroftardis commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +  -Tokens will use to pay for the transactions on the Casper Network (involving ERC-20 tokens). Follow the [transfer tokens](https://casper.network/docs/workflow/token-transfer#2-the-faucet) guide to
This line is very confusing, what are we trying to point out here?

2022-01-13 15:28 UTC, darthsiroftardis commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +make prepare
This is incorrect, this will just setup the dependencies for the contract and won't actually build the contract. 

```suggestion
make prepare
make build-contracts
```

The `make build-contracts` command will actually build the WASM

2022-01-13 15:45 UTC, Buddhika-Pathirathna commented on source/docs/casper/dapp-dev-guide/tutorials/erc20/deploy.md
> +  -Tokens will use to pay for the transactions on the Casper Network (involving ERC-20 tokens). Follow the [transfer tokens](https://casper.network/docs/workflow/token-transfer#2-the-faucet) guide to
It tells why tokens are used in this context - I have altered the wording with new changes

2022-01-13 16:30 UTC, darthsiroftardis approved these changes

2022-01-14 14:20 UTC, hoffmannjan approved these changes

2022-01-14 15:00 UTC, merged