Add initial changes to cep-47 introduction and prepare sections
casper-network/docs pull request #196
Opened 2022-01-21 18:00 UTC by Buddhika-Pathirathna

### Related links
-

### Changes

// Added Introduction and Preparetion content to CEP-47 contract with sidebar.config file changes

### Notes
Will be completing CEP-47 tutorial  deploy, implementation and test sections with two more separate cards.

2022-02-18 12:01 UTC, deuszex commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +CEP-47 standard contains endpoints to enable the NFT functionalities. The basic attributes of tokens are addressed by *name*, *symbol*, *total_supply*, and *balance_of* endpoints.The token ownership
`name`, `symbol`, `meta`, `total_supply` are details of the whole contract.
`balance_of`, `get_token_by_index` get details of tokens related to a specific account.
`owner_of`, `token_meta` are for details of a specific token.
All of the above can only be called from inside contracts, as they return data.

2022-02-25 05:35 UTC, Buddhika-Pathirathna commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +While [ERC-721](https://eips.ethereum.org/EIPS/eip-721) is the original name for the standard given in Ethereum blockchain, CEP-47 is the customized standard for the Casper platform. CEP-47 standard
> `the standards originate from Ethereum ecosystem are not the best choice for the Casper platform` is horrible phrasing, suggests that we cannot do what eth can

Thanks, @deuszex - I grabbed that from PR 47 (file - [./0047-casper-nft-protocol.md](https://github.com/casper-network/ceps/pull/47/files#) -> line 12-14 ). Could you please suggest a good alternative way to describe it or do you think it's better to remove that part?

2022-02-25 05:44 UTC, Buddhika-Pathirathna commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +CEP47 takes full advantage of the URef feature to optimize smart contracts interactions. It also uses the Groups feature to optimize gas costs. Since this is a different type of token there are speci
This part is also taken from [Cep-47 - Casper NFT Protocol](https://github.com/casper-network/ceps/pull/47/files#) file , line numbers 16 17. Appreciate if you can re-phrase it in a better way, suggest any new idea or verify the deletion of that part. Thanks

2022-02-25 20:52 UTC, ipopescu requested changes
@Buddhika-Pathirathna thank you for this section! I have reviewed it and left suggested changes. Please let me know if you have questions.

2022-02-25 20:52 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +### ERC-721 Standard
```suggestion
### The NFT Standard on Ethereum
```

2022-02-25 20:52 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +ERC-721 is the standard defined to implement the [non-fungible tokens](/docs/glossary/N#non-fungible-token) inside Ethereum blockchain. This standard defines a minimum interface a smart contract shou
```suggestion
[ERC-721](https://eips.ethereum.org/EIPS/eip-721) is the standard defined to implement NFTs on the Ethereum blockchain. This standard defines a minimum interface a smart contract should implement to manage, own, and trade unique tokens. 
```

2022-02-25 20:52 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +## ERC-721 Implementation within Casper Network
```suggestion
## The NFT Standard on Casper
```

2022-02-25 20:52 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +# Introduction
```suggestion
# The NFT Standard on Casper (CEP-47)
```

2022-02-25 20:52 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +This tutorial takes you through the NFT implementation of the Casper Network. Before diving deep into the Casper NFT implementation, let's cover some knowledge on overall NFT design. The following se
```suggestion
This tutorial takes you through the standard of implementing [non-fungible tokens](/docs/glossary/N#non-fungible-token) on the Casper Network. Before diving into the Casper NFT implementation, let's cover some knowledge on overall NFT design. The following sections illustrate the origin and the development of NFTs in the blockchain domain.
```

2022-02-25 20:52 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +This tutorial takes you through the NFT implementation of the Casper Network. Before diving deep into the Casper NFT implementation, let's cover some knowledge on overall NFT design. The following se
I moved the NFT definition up, where it is first used.

2022-02-25 20:52 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +ERC-721 is the standard defined to implement the [non-fungible tokens](/docs/glossary/N#non-fungible-token) inside Ethereum blockchain. This standard defines a minimum interface a smart contract shou
Please double check that links and definitions are mentioned when a term is first used (such as ERC-721, CEP-47).

2022-02-25 20:52 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +While [ERC-721](https://eips.ethereum.org/EIPS/eip-721) is the original name for the standard given in Ethereum blockchain, CEP-47 is the customized standard for the Casper platform. CEP-47 standard
```suggestion
[CEP-47](https://github.com/casper-ecosystem/casper-nft-cep47) is the NFT standard for the Casper blockchain, supporting the unique traits of the Casper Virtual Machine and its gas-efficient design. 
```

2022-02-25 20:52 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +While [ERC-721](https://eips.ethereum.org/EIPS/eip-721) is the original name for the standard given in Ethereum blockchain, CEP-47 is the customized standard for the Casper platform. CEP-47 standard
I recommend simplifying this and keeping it short and sweet -- unless you can get more information from developers about the "unique traits" and describe those further. Proposed commit below.

2022-02-25 20:52 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +## CEP-47 Standard
```suggestion
```

2022-02-25 20:52 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +## CEP-47 Standard
Suggesting to remove the title and merge the content with the previous paragraph.

2022-02-25 20:52 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +CEP47 takes full advantage of the URef feature to optimize smart contracts interactions. It also uses the Groups feature to optimize gas costs. Since this is a different type of token there are speci
```suggestion
CEP-47 takes full advantage of [unforgeable references](https://casper.network/docs/design/uref) to store values and manage permissions to them. The standard also takes advantage of other access control features (such as groups). We recommend exploring the [main functions](./index#cep-47-function-types) of the [contract](https://github.com/casper-ecosystem/casper-nft-cep47/blob/master/cep47/bin/cep47_token.rs) to understand the standard further.
```

2022-02-25 20:52 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +CEP47 takes full advantage of the URef feature to optimize smart contracts interactions. It also uses the Groups feature to optimize gas costs. Since this is a different type of token there are speci
1. I suggest simplifying (see commit suggestion), unless you can find out more about how those optimizations can be made. However, since this is an introduction, you can talk more about the optimizations in another section.
2. Please add the Groups explanation to the glossary, or somewhere in the design section: 
"The Groups feature provides access control to a contract's runtime context. It is used only once to restrict the use of the constructor entry_point, which sets up necessary data storage in the contract context."
3. Once you have a link, please add it as a reference where you first mention "Groups".

2022-02-25 20:52 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +CEP-47 standard contains endpoints to enable the NFT functionalities. The basic attributes of tokens are addressed by *name*, *symbol*, *total_supply*, and *balance_of* endpoints.The token ownership
@Buddhika-Pathirathna I recommend changing this paragraph by adding a list and a short sentence about each function. Then add what @deuszex mentioned as a note.

```
The CEP-47 standard contains the following endpoints:
*name* - ...
*symbol* - ...
*total_supply* - ...
*balance_of* - ...
*owner_of* - ...
*get_token_by_index* - ...
*meta* - ...
*token_meta* - ...
*update_token_meta*  - ...
*mint* - ...
*mint_copies* - ...
*burn* - ...
*transfer* - ...
*transfer_from* - ...
*approve* - ...
*get_approved*  - ...

:::note
These functions can only be called from inside contracts, as they return data:
*name*, *symbol*, *meta*, and *total_supply* return details regarding the whole contract
*balance_of* and *get_token_by_index* retrieve details of tokens related to a specific account
*owner_of* and *token_meta* retrieve the details of a specific token
:::
```

2022-02-25 20:52 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +If you haven't read [Writing Rust Contracts on Casper](../../writing-contracts/rust.md), we recommend you start there to learn more about smart contracts.
```suggestion
```

2022-02-25 20:52 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +If you haven't read [Writing Rust Contracts on Casper](../../writing-contracts/rust.md), we recommend you start there to learn more about smart contracts.
I think it is best to remove this line.

2022-02-28 14:01 UTC, Buddhika-Pathirathna commented on source/docs/casper/glossary/N.md
> +## Non-Fungible Token (NFT) {#non-fungible-token}
Thanks a lot @Iulia for taking time to review, I will add the changes soon

2022-03-04 13:56 UTC, ipopescu reviewed
@Buddhika-Pathirathna thank you for the updates! Almost there!
I have some final suggestions and if you agree with them, please push the new commits and I will approve the PR. Thanks so much!

2022-03-04 13:56 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +### CEP-47 Function Types
```suggestion
### CEP-47 Functions
```

2022-03-04 13:56 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +CEP-47 standard contains following endpoints to enable the NFT functionalities.
```suggestion
The CEP-47 standard contains the following functions to enable NFTs. 
```

2022-03-04 13:56 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +The CEP-47 standard contains the following endpoints:
Delete this line, as it seems to be duplicated.
```suggestion
```

2022-03-04 13:56 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +Metadata endpoints will be used by other smart contracts
I think this line should also be deleted.
```suggestion
```

2022-03-04 13:56 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +CEP-47 takes full advantage of [unforgeable references](/docs/design/uref) to store values and manage permissions to them. The standard also takes advantage of other access control features (such as
```suggestion
The Casper NFT standard takes full advantage of [unforgeable references](/docs/design/uref) to store values and manage permissions to them. It also takes advantage of other access control features (such as [groups](/docs/glossary/G#groups)). We recommend exploring the [main functions](../cep47/#cep-47-function-types) of the [contract](https://github.com/casper-ecosystem/casper-nft-cep47/blob/master/cep47/bin/cep47_token.rs) to understand the standard further.
```

2022-03-04 13:56 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +- [*meta*](https://github.com/casper-ecosystem/casper-nft-cep47/blob/09b40b0caf4cfc6f73d1e5f7d5b9c868228f7621/cep47/bin/cep47_token.rs#L56-L59) - Returns the metadata of NFT
```suggestion
- [*meta*](https://github.com/casper-ecosystem/casper-nft-cep47/blob/09b40b0caf4cfc6f73d1e5f7d5b9c868228f7621/cep47/bin/cep47_token.rs#L56-L59) - Returns the metadata of the NFT contract
```

2022-03-04 13:56 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +- [*balance_of*](https://github.com/casper-ecosystem/casper-nft-cep47/blob/09b40b0caf4cfc6f73d1e5f7d5b9c868228f7621/cep47/bin/cep47_token.rs#L68-L72) - Returns an amount of NFT instances the `owner`
```suggestion
- [*balance_of*](https://github.com/casper-ecosystem/casper-nft-cep47/blob/09b40b0caf4cfc6f73d1e5f7d5b9c868228f7621/cep47/bin/cep47_token.rs#L68-L72) - Returns the amount of NFT tokens the `owner` holds
```

2022-03-04 13:56 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +- [*get_token_by_index*](https://github.com/casper-ecosystem/casper-nft-cep47/blob/09b40b0caf4cfc6f73d1e5f7d5b9c868228f7621/cep47/bin/cep47_token.rs#L75-L80) - Getter for token index. Tokens are stor
I don't understand this explanation. Do you mean this:

```suggestion
- [*get_token_by_index*](https://github.com/casper-ecosystem/casper-nft-cep47/blob/09b40b0caf4cfc6f73d1e5f7d5b9c868228f7621/cep47/bin/cep47_token.rs#L75-L80) - Retrieves the NFT token at a specific index
```

2022-03-04 13:56 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +- [*owner_of*](https://github.com/casper-ecosystem/casper-nft-cep47/blob/09b40b0caf4cfc6f73d1e5f7d5b9c868228f7621/cep47/bin/cep47_token.rs#L83-L87) - Getter for the owner of a given token
```suggestion
- [*owner_of*](https://github.com/casper-ecosystem/casper-nft-cep47/blob/09b40b0caf4cfc6f73d1e5f7d5b9c868228f7621/cep47/bin/cep47_token.rs#L83-L87) - Retrieves the owner of a given token
```

2022-03-04 13:56 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +- [*token_meta*](https://github.com/casper-ecosystem/casper-nft-cep47/blob/09b40b0caf4cfc6f73d1e5f7d5b9c868228f7621/cep47/bin/cep47_token.rs#L90-L94) - Getter for the metadata for a given token
```suggestion
- [*token_meta*](https://github.com/casper-ecosystem/casper-nft-cep47/blob/09b40b0caf4cfc6f73d1e5f7d5b9c868228f7621/cep47/bin/cep47_token.rs#L90-L94) - Retrieves the metadata for a given token
```

2022-03-04 13:56 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +- [*mint_copies*](https://github.com/casper-ecosystem/casper-nft-cep47/blob/09b40b0caf4cfc6f73d1e5f7d5b9c868228f7621/cep47/bin/cep47_token.rs#L116-L124) - Creates for an address, several tokens with
```suggestion
- [*mint_copies*](https://github.com/casper-ecosystem/casper-nft-cep47/blob/09b40b0caf4cfc6f73d1e5f7d5b9c868228f7621/cep47/bin/cep47_token.rs#L116-L124) - For a given address, this function creates several tokens with specific IDs but with the same metadata
```

2022-03-04 13:56 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +- [*burn*](https://github.com/casper-ecosystem/casper-nft-cep47/blob/09b40b0caf4cfc6f73d1e5f7d5b9c868228f7621/cep47/bin/cep47_token.rs#L127-L133) - Destroys the given tokens for a given account
```suggestion
- [*burn*](https://github.com/casper-ecosystem/casper-nft-cep47/blob/09b40b0caf4cfc6f73d1e5f7d5b9c868228f7621/cep47/bin/cep47_token.rs#L127-L133) - Destroys the tokens in the account given
```

2022-03-04 13:56 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +- [*get_approved*](https://github.com/casper-ecosystem/casper-nft-cep47/blob/09b40b0caf4cfc6f73d1e5f7d5b9c868228f7621/cep47/bin/cep47_token.rs#L164-L169) - Getter function to see if the owner has giv
Suggestion to write this in plain English:
```suggestion
- [*get_approved*](https://github.com/casper-ecosystem/casper-nft-cep47/blob/09b40b0caf4cfc6f73d1e5f7d5b9c868228f7621/cep47/bin/cep47_token.rs#L164-L169) - Retrieves information about the rights to transfer tokens from another account
```

2022-03-04 13:56 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +- [*approve*](https://github.com/casper-ecosystem/casper-nft-cep47/blob/09b40b0caf4cfc6f73d1e5f7d5b9c868228f7621/cep47/bin/cep47_token.rs#L155-L161) - Give an account 'approved rights' to transfer to
Suggestion to write this in plain English:
```suggestion
- [*approve*](https://github.com/casper-ecosystem/casper-nft-cep47/blob/09b40b0caf4cfc6f73d1e5f7d5b9c868228f7621/cep47/bin/cep47_token.rs#L155-L161) - Gives another account the right to transfer tokens from this account
```

2022-03-04 13:56 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/index.md
> +- [*mint*](https://github.com/casper-ecosystem/casper-nft-cep47/blob/09b40b0caf4cfc6f73d1e5f7d5b9c868228f7621/cep47/bin/cep47_token.rs#L106-L113) - Creates a list of tokens with the given ids and the
```suggestion
- [*mint*](https://github.com/casper-ecosystem/casper-nft-cep47/blob/09b40b0caf4cfc6f73d1e5f7d5b9c868228f7621/cep47/bin/cep47_token.rs#L106-L113) - Creates a list of tokens for a specific recipient, given the token IDs and their metadata, paired in order
```

2022-03-07 10:10 UTC, deuszex commented on source/docs/casper/glossary/G.md
> +The Groups feature provides access control to a contract's runtime context. It is used only once to restrict the use of the constructor entry_point, which sets up necessary data storage in the contra
contracts*

2022-03-07 11:50 UTC, Buddhika-Pathirathna commented on source/docs/casper/glossary/G.md
> +The Groups feature provides access control to a contract's runtime context. It is used only once to restrict the use of the constructor entry_point, which sets up necessary data storage in the contra
I would like to get @ipopescu 's input for this.

2022-03-07 16:45 UTC, ipopescu commented on source/docs/casper/glossary/G.md
> +The Groups feature provides access control to a contract's runtime context. It is used only once to restrict the use of the constructor entry_point, which sets up necessary data storage in the contra
Based on our group discussion, providing a wider definition and clarifying the possessive form for the contract.
```suggestion
The *user groups* feature provides access control to the entry points of a contract by creating a new user group for that contract (versioned or not). This feature restricts the use of the constructor entry_point, which sets up the necessary data storage in the runtime context that belongs to the contract. Here is how it works:
- User groups associate a set of URefs with a label.
- The entry points on a contract can accept a list of labels
- The runtime checks that a URef from at least one of the allowed groups is present in the caller's context before execution. 
```

2022-03-07 16:46 UTC, ipopescu approved these changes
Good to go! Thanks, @Buddhika-Pathirathna!

2022-03-07 17:55 UTC, ipopescu reviewed
Adding a note on the blank pages as this may go out live if we publish it before pr 206 (this depends on how 206 goes).

2022-03-07 17:55 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/implementation.md
> +# Contract Implementation
```suggestion
# Contract Implementation

Coming soon!
```

2022-03-07 17:55 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/deploy.md
> +# Contract Deployment
```suggestion
# Contract Deployment

Coming soon!
```

2022-03-07 17:55 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/cep47/test.md
> +# Testing Framework
```suggestion
# Testing Framework

Coming soon!
```

2022-03-07 18:23 UTC, merged

2022-03-07 18:23 UTC, ipopescu commented
Great work, @Buddhika-Pathirathna! This has been merged.