Adding initial draft changes to Card - 285 -  how to write smart cont…
casper-network/docs pull request #308
Opened 2022-03-30 18:00 UTC by Buddhika-Pathirathna

…racts

### Related links

Card - [285](https://github.com/casper-network/docs/issues/285)

### Changes
- Changed the folder hierarchy
- Added a new folder called 'Casper Smart Contracts' and added two pages under that - 'Overview' and 'Create Basic Smart Contract'
- Added some content grabbed from google as well
- Added 3 images to support content - Not sure about the technical accuracy

### Notes
- This is a very draft and may need more technical corrections

2022-03-30 18:02 UTC, Buddhika-Pathirathna commented on source/docs/casper/dapp-dev-guide/smart-contracts/create-smart-contract.md
> +
This file is not completed yet, planning to add content with code snippets and related explanation as the second step of this card

2022-03-30 18:03 UTC, Buddhika-Pathirathna commented on source/docs/casper/dapp-dev-guide/smart-contracts/overview.md
> +Casper smart contracts work as below,
Need to verify the technical terms, flow, and ideas integration of this section

2022-03-30 18:05 UTC, Buddhika-Pathirathna commented on source/docs/casper/dapp-dev-guide/smart-contracts/overview.md
> +
Do we need to mention about 'create_contract' method at this point (with code snippets)? Because it seems that the code actually creates the content.

2022-03-30 18:06 UTC, Buddhika-Pathirathna commented on source/docs/casper/dapp-dev-guide/smart-contracts/overview.md
> +### Difference between Smart Contract and Wasm
I thought it is better to add this section because we generally had confusion, please verify.

2022-04-01 15:10 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/smart-contracts/create-smart-contract.md
> +<img src={useBaseUrl("/image/smart-contract/smart-contract-flow.png")} alt="create-smart-contract-flow" width="400"/>
I really don't think we need this image. Consider including some pseudo-code if you would really like to demonstrate this. For example:
<img width="505" alt="Screen Shot 2022-04-01 at 5 09 00 PM" src="https://user-images.githubusercontent.com/4185994/161291368-04c1853f-7bc7-440f-9f42-400b5df6432c.png">

2022-04-01 17:21 UTC, Buddhika-Pathirathna reviewed
Please note that I didn't run the Grammer check for this latest context for the time being.

2022-04-19 18:46 UTC, ipopescu requested changes
Please rebase against the main branch.

2022-04-19 18:48 UTC, ipopescu commented
@Buddhika-Pathirathna Please rebase against the dev branch.

2022-04-27 12:51 UTC, ipopescu commented
@Buddhika-Pathirathna I think we need to close this PR since there is another one open.

2022-04-27 12:55 UTC, Buddhika-Pathirathna commented
> @Buddhika-Pathirathna I think we need to close this PR since there is another one open.

Sure, I will do that Iulia. Thanks for checking.

2022-04-27 12:55 UTC, closed without merging