Checksummed hex encoding
casper-network/docs pull request #387
Opened 2021-10-27 20:44 UTC by nilz3ro

Adds documentation for the new checksummed-hex encoding feature.

2021-11-11 14:33 UTC, ipopescu requested changes
@nilz3ro, thanks so much for this article! Please update the version before merging (and thus updating the public documentation). I've submitted a few changes regarding formatting and links. @Buddhika-Pathirathna or @Gloreen, could you also take a look at this PR? Also, @nilz3ro, for future articles, please use the new repository: https://github.com/casper-network/docs-app. I can help move this PR to the new docs once it is merged here (we're keeping the repositories in sync for now).

2021-11-11 14:33 UTC, ipopescu commented on implementation/checksummed-hex.rst
> +Checksummed Hex Encoding
I propose using "checksum" rather than "checksummed".

2021-11-11 14:33 UTC, ipopescu commented on implementation/checksummed-hex.rst
> +The checksummed hex encoding spec was defined in **CEP-57** and implemented in **1.x.x**.
I suggest adding the version or removing "and implemented ...".

2021-11-11 14:33 UTC, ipopescu commented on implementation/checksummed-hex.rst
> +declared in :ref:`cep-57 <https://github.com/casper-network/ceps/blob/master/text/0057-checksummed-addresses.md>` and implemented in **version**.
Please add the version here, or take out that piece.

2021-11-11 14:33 UTC, ipopescu commented on implementation/checksummed-hex.rst
> +You can find the implementation on github **link**
Please add the link. Example: `GitHub <https://github.com/casper-network/casper-node/blob/dev/types/src/checksummed_hex.rs>`_

2021-11-11 14:33 UTC, ipopescu commented on implementation/checksummed-hex.rst
> +Version **1.x.x** is backwards-compatible with lower-hex encoded keys, so if you use a public key that is encoded in lowercase hex,
Before merging and updating the live documentation, please finalize the version and this TODO.

2021-11-11 17:38 UTC, nilz3ro commented on implementation/checksummed-hex.rst
> +Checksummed Hex Encoding
There has been a bit of back-and-forth on this one, @Fraser999 do you have an opinion on this?

2021-11-19 20:08 UTC, sacherjj commented on implementation/checksummed-hex.rst
> +A checksum hex encoding is a format that includes an embedded checksum to avoid copy errors when entering account addresses. While the checksum hex format protects account addresses, it also protects
```suggestion
A checksum hex encoding is a format that includes an embedded checksum to avoid copy errors when entering account addresses. While the checksum hex format protects account addresses, it also protects all hex-encoded values. For more details, look at the specification defined in `CEP-57 <https://github.com/casper-network/ceps/blob/master/text/0057-checksummed-addresses.md>`_.
```

2021-11-19 20:10 UTC, merged

2021-11-19 20:25 UTC, ipopescu commented on implementation/checksummed-hex.rst
> +Checksummed Hex Encoding
@nilz3ro I will use "checksummed" when I port this document to docs-app.