Adding the session code unit testing tutorial
casper-network/docs pull request #415
Opened 2022-05-06 10:09 UTC by Buddhika-Pathirathna

### Related links

Related cards - [330](https://github.com/casper-network/docs/issues/330) and  [331](https://github.com/casper-network/docs/issues/331) 

### Changes
- Added the steps to build the unit test program for the session code

### Notes
 - Some links are kept as 'todo' since the content is not yet finalized and merged.
 - Some sections need verification on whether to keep or remove from the tutorial - Added the comment to those.

2022-05-06 10:10 UTC, Buddhika-Pathirathna commented on source/docs/casper/dapp-dev-guide/testing-session-code.md
> +The overall test program structure should be as below:
Please verify whether to keep or remove this part.

2022-05-06 10:11 UTC, Buddhika-Pathirathna commented on source/docs/casper/dapp-dev-guide/testing-session-code.md
> +This section describes how to test a session code based on the unit testing mechanism. It's recommended to follow the [understanding session code](todo) section before starting this tutorial. Here, w
Link will be added after the code merge.

2022-05-06 10:17 UTC, Buddhika-Pathirathna commented on source/docs/casper/dapp-dev-guide/testing-session-code.md
> +```
Please verify whether to keep or remove this part.

2022-05-10 18:22 UTC, ACStoneCL requested changes
I added a few flow suggestions and changed instances of 'wasm' to 'Wasm'.

Also, we're trying to avoid the use of the 'Adder' contract, but I don't think the addition code is intrinsic to this document as written, so it might be fairly easy to quick-swap out for another contract.

I think the content itself in relation to the testing process is good.

2022-05-10 18:22 UTC, ACStoneCL commented on source/docs/casper/dapp-dev-guide/testing-session-code.md
> +The session code executes in the context of the account which sent the deploy containing that session code. In this scenario, since the session code is executing in the corresponding account's contex
```suggestion
The session code executes in the context of the account which sent the deploy. In this scenario, since the session code is executing in the corresponding account's contexts, it has the same access permissions as the corresponding account. 
```

2022-05-10 18:22 UTC, ACStoneCL commented on source/docs/casper/dapp-dev-guide/testing-session-code.md
> +In this tutorial, we use the example used in the [sample contract](#sample-contract-used-to-build-the-session-code) section to build the test program.
```suggestion
In this tutorial, we use the example from the [sample contract](#sample-contract-used-to-build-the-session-code) section to build the test program.
```

2022-05-10 18:22 UTC, ACStoneCL commented on source/docs/casper/dapp-dev-guide/testing-session-code.md
> +- `Cargo.toml` - This is the file with project configurations
```suggestion
- `Cargo.toml` - This is the file with project configurations.
```

2022-05-10 18:22 UTC, ACStoneCL commented on source/docs/casper/dapp-dev-guide/testing-session-code.md
> +- `casper-execution-engine` - This imports the functionalities of the execution engine which enables the wasm execution. Each node contains an instance of an execution engine within it.
```suggestion
- `casper-execution-engine` - This imports the functionalities of the execution engine which enables the Wasm execution. Each node contains an instance of an execution engine within it.
```

I think we've finalized 'Wasm' as the preferred format/abbreviation, but I'm not 100% sure on that in this context. I've been using Wasm in all instances.

2022-05-10 18:22 UTC, ACStoneCL commented on source/docs/casper/dapp-dev-guide/testing-session-code.md
> +- `casper-engine-test-support` - This is a helper crate that provides the interface to interact with the execution engine to execute the wasm.
```suggestion
- `casper-engine-test-support` - This is a helper crate that provides the interface to interact with the execution engine to execute the Wasm.
```

2022-05-10 18:22 UTC, ACStoneCL commented on source/docs/casper/dapp-dev-guide/testing-session-code.md
> +- `casper-types` - These are types used in the program.
```suggestion
- `casper-types` - These are Casper's custom types used in the program.
```

2022-05-10 18:22 UTC, ACStoneCL commented on source/docs/casper/dapp-dev-guide/testing-session-code.md
> +- `PathBuf` - This package supports loading the session code wasm.
```suggestion
- `PathBuf` - This package supports loading the session code Wasm.
```

2022-05-10 18:22 UTC, ACStoneCL commented on source/docs/casper/dapp-dev-guide/testing-session-code.md
> +
We've been avoiding the use of the 'Adder' contract due to it's implication that basic math functions must be coded by developers, rather than being available intrinsically within the Casper platform.

2022-05-10 18:22 UTC, ACStoneCL commented on source/docs/casper/dapp-dev-guide/testing-session-code.md
> +The above code snippet starts by initializing the test builder and the genesis request. Then, the contract wasm is loaded to the session code object.  After that, the deploy object is created using t
```suggestion
The above code snippet starts by initializing the test builder and the genesis request. Then, the contract Wasm is loaded to the session code object.  After that, the deploy object is created using the details like payment method, contract Wasm, and account address. Then, the deploy object is passed to the created execute request. Finally, the execution engine is invoked to process the execute request. Refer to [creating a test function](/dapp-dev-guide/testing/#deploy-the-smart-contract) for more details about each function. 
```

2022-05-10 18:22 UTC, ACStoneCL commented on source/docs/casper/dapp-dev-guide/testing-session-code.md
> +The below code snippet retrieves the value of interest which is named as `answer`. It is stored under the URef which is a part of the account's name keys. Then, the formatted value is asserted agains
```suggestion
The below code snippet retrieves the value of interest which is named as `answer`. It is stored under the URef which is a part of the account's named keys. Then, the formatted value is asserted against our expected value to verify the success of the test program.
```

2022-05-12 18:23 UTC, darthsiroftardis requested changes
Some changes that need to occur, additionally I'd like see to @ACStoneCL 's feedback incorporated as well

2022-05-12 18:23 UTC, darthsiroftardis commented on source/docs/casper/dapp-dev-guide/testing-session-code.md
> +// Set up genesis node
```suggestion
// Execute the genesis process
```

2022-05-13 10:56 UTC, Buddhika-Pathirathna commented on source/docs/casper/dapp-dev-guide/testing-session-code.md
> +    #[test]
I changed the keywords in this section, please review.

2022-05-13 11:11 UTC, Buddhika-Pathirathna commented on source/docs/casper/dapp-dev-guide/testing-session-code.md
> +mod <your-unit-test-name>{
It's a mistake - here , 'mod' should be 'fn' - please review

2022-05-13 11:13 UTC, Buddhika-Pathirathna commented on source/docs/casper/dapp-dev-guide/testing-session-code.md
> +
So @darthsiroftardis - Is it ok to keep the adder example in this tutorial?

2022-05-13 11:15 UTC, Buddhika-Pathirathna commented
Thanks a lot @ACStoneCL and @darthsiroftardis for taking the time to review this PR. @darthsiroftardis there are a few other points that need your attention, I have tagged you at those - those are regarding whether to keep pr remove the content.

2022-05-18 13:45 UTC, darthsiroftardis reviewed
Some changes are needed here

2022-05-18 13:45 UTC, darthsiroftardis commented on source/docs/casper/dapp-dev-guide/testing-session-code.md
> +- `casper_engine_test_support` - This package provides the interfaces to perform the tests using its' builder classes.
```suggestion
- `casper_engine_test_support` - This package provides the interfaces to write tests and interact with an instance of the execution engine.
```

2022-05-18 13:45 UTC, darthsiroftardis commented on source/docs/casper/dapp-dev-guide/testing-session-code.md
> +- `casper_execution_engine` - This package imports the required classes from the execution engine including the genesis node and related functionalities.
```suggestion
- `casper_execution_engine` - This package imports the Casper execution engine itself.
```

2022-05-18 13:45 UTC, darthsiroftardis commented on source/docs/casper/dapp-dev-guide/testing-session-code.md
> +The overall test program structure should be as below:
We can remove this @Buddhika-Pathirathna

2022-05-18 13:45 UTC, darthsiroftardis commented on source/docs/casper/dapp-dev-guide/testing-session-code.md
> +
Yeah, I think for the purposes of this tutorial I am okay with it, our focus should be what the tests look like as opposed to the code we're testing

2022-05-18 13:45 UTC, darthsiroftardis commented on source/docs/casper/dapp-dev-guide/testing-session-code.md
> +```
I think we can remove this

2022-05-18 16:55 UTC, Buddhika-Pathirathna commented on source/docs/casper/dapp-dev-guide/testing-session-code.md
> +The overall test program structure should be as below:
Done.

2022-05-18 16:55 UTC, Buddhika-Pathirathna commented on source/docs/casper/dapp-dev-guide/testing-session-code.md
> +Following is a code sample of a basic unit test for adding two numbers. `should_add_two_numbers` is the name given to this specific unit test.
Kept as it is.

2022-05-18 16:57 UTC, Buddhika-Pathirathna commented on source/docs/casper/dapp-dev-guide/testing-session-code.md
> +```
Done.

2022-05-18 16:59 UTC, Buddhika-Pathirathna commented on source/docs/casper/dapp-dev-guide/testing-session-code.md
> +    #[test]
Adjusted.

2022-05-19 10:29 UTC, Buddhika-Pathirathna commented
> 

Review feedback addressed.

2022-05-19 15:24 UTC, ACStoneCL approved these changes
Looks good to me.

2022-05-20 20:42 UTC, darthsiroftardis approved these changes

2022-05-21 01:15 UTC, merged