424 NCTL Testing Documentation
casper-network/docs pull request #452
Opened 2022-05-18 13:44 UTC by ACStoneCL

### Related links

[Improve testing section - NCTL integration tests #424](https://github.com/casper-network/docs/issues/424)

### Changes

Added a document that describes the process of using NCTL to test smart contracts.

### Notes

Ran locally without issue.

2022-05-23 17:24 UTC, ipopescu approved these changes
Very well written and technically correct. I've left minor suggestions, therefore approving.

2022-05-23 17:24 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/nctl-test.md
> +NCTL effectively simulates a live Casper network. The process for sending a `Deploy` to an NCTL-based network is therefore similar to doing so on a live network.
I would move these 2 sentences in the intro.

2022-05-23 17:24 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/nctl-test.md
> +This document assumes that you setup your NCTL network using the standard settings in a directory called */casper/*
```suggestion
This document assumes that you setup your NCTL network using the standard settings in a directory called */casper/*.
```

2022-05-23 17:24 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/nctl-test.md
> +
Suggestion to re-arrange this a bit:
```suggestion
The previous command sent the `Deploy` to the NCTL network, but we recommend verifying deploy execution before continuing. The `deploy_hash` received in the response allows you to query the `Deploy`'s status. 

To query the `Deploy`'s status, you will pass both the `deploy_hash` and the same `node-address` from above using the following command. This will return either an error message in the event of failure or the `Deploy` details if it succeeds.
```

2022-05-24 18:25 UTC, TomVasile commented on source/docs/casper/dapp-dev-guide/nctl-test.md
> +## Testing Contracts on the Casper Testnet
Nit: Just doesn't seem relevant to mention testing on Testnet in a doc about NCTL.

2022-05-24 18:52 UTC, ACStoneCL commented on source/docs/casper/dapp-dev-guide/nctl-test.md
> +This document assumes that you setup your NCTL network using the standard settings in a directory called */casper/*.
I've rectified this across the document to `/`

2022-05-24 18:53 UTC, ACStoneCL commented on source/docs/casper/dapp-dev-guide/nctl-test.md
> +casper-client get-deploy 8e6309cc37bc58d8fedc1094ee1bd264a636d39fc0e05b5e1d72d98f7b6faf13 -n http://localhost:11101/rpc
@TomVasile Would this be true for all uses within NCTL - such as for the put-deploy and get-account-info as well?

2022-05-24 19:48 UTC, TomVasile commented on source/docs/casper/dapp-dev-guide/nctl-test.md
> +casper-client get-deploy 8e6309cc37bc58d8fedc1094ee1bd264a636d39fc0e05b5e1d72d98f7b6faf13 -n http://localhost:11101/rpc
Correct, it applies everywhere.  Although using the installed client may work, there is no guarantee. It really depends on which version of the code base is checked out.

2022-05-24 22:49 UTC, TomVasile requested changes

2022-05-24 22:49 UTC, TomVasile commented on source/docs/casper/dapp-dev-guide/nctl-test.md
> +3) [Setup NCTL](../dapp-dev-guide/setup-nctl.md) on your system
`setup-nctl.md` has no mention that you must clone down the client (it only mentions the launcher).  Should be added there with a note to match the client to the version of node checked out.

ie. testing contract against current dev

```
casper-node: dev 
casper-client-rs: dev
```

If there is no matching branch for `casper-client-rs` use the closest version. 

ie.
```
casper-node: 1.4.6
casper-client-rs: 1.4.5 (Note: this is a tag on main they will need to checkout)
```

Without the client being present in the same directory as node, `nctl-compile` will fail.

2022-05-24 22:49 UTC, TomVasile commented on source/docs/casper/dapp-dev-guide/nctl-test.md
> +3) [Setup NCTL](../dapp-dev-guide/setup-nctl.md) on your system
`setup-nctl.md` has no mention that you must clone down the client (it only mentions the launcher).  Should be added there with a note to match the client to the version of node checked out.

ie. testing contract against current dev

```
casper-node: dev 
casper-client-rs: dev
```

Without the client being present in the same directory as node, `nctl-compile` will fail.

2022-05-25 15:08 UTC, merged

2022-06-01 05:39 UTC, Buddhika-Pathirathna commented on source/docs/casper/dapp-dev-guide/nctl-test.md
> +
Isn't it better to re-arrange the content of 'put-deploy' as in the below links (add the code snippet first and then the field explanations under it)
- https://docs.casperlabs.io/dapp-dev-guide/writing-contracts/rust/#locked-contracts
- https://docs.casperlabs.io/workflow/delegate/#sending-the-delegation-deploy

2022-06-01 06:33 UTC, Buddhika-Pathirathna commented on source/docs/casper/dapp-dev-guide/nctl-test.md
> +
Same suggestion as above comment to adjust the content.

- https://docs.casperlabs.io/dapp-dev-guide/writing-contracts/rust/#locked-contracts
- https://docs.casperlabs.io/workflow/delegate/#sending-the-delegation-deploy

2022-06-01 06:49 UTC, Buddhika-Pathirathna commented on source/docs/casper/dapp-dev-guide/nctl-test.md
> +
'note about gas prices' link is not working for me - it yields 'page not found' error with url 'http://localhost:3001/dapp-dev-guide/nctl-test/dapp-dev-guide/sending-deploys/#a-note-about-gas-price'

2022-06-01 06:55 UTC, Buddhika-Pathirathna commented on source/docs/casper/dapp-dev-guide/nctl-test.md
> +
'set up' instead of 'setup'?

2022-06-01 06:56 UTC, Buddhika-Pathirathna commented on source/docs/casper/dapp-dev-guide/nctl-test.md
> +* The **session path**, defining the location of the Wasm bearing file for the `Deploy`. It appears in our example as `--session-path <PATH>` but you must define the path to your specific file.
'defining' --> 'defines'

2022-06-01 07:02 UTC, Buddhika-Pathirathna commented on source/docs/casper/dapp-dev-guide/nctl-test.md
> +After calling your installed contract, you can verify that the contract behaved as expected by observing the associated change in [global state](dapp-dev-guide/installing-contracts/#querying-global-s
'global state' link doesn't work for me - gives 'Page Not Found' with 'http://localhost:3001/dapp-dev-guide/nctl-test/dapp-dev-guide/installing-contracts/#querying-global-state'

2022-06-01 07:03 UTC, Buddhika-Pathirathna commented on source/docs/casper/dapp-dev-guide/nctl-test.md
> +
'basic smart contract tutorial' link doesn't work for me - gives 'Page Not Found' with 'http://localhost:3001/dapp-dev-guide/nctl-test/dapp-dev-guide/writing-contracts/rust/'

- correct link seems - http://localhost:3001/dapp-dev-guide/writing-contracts/rust/

2022-06-01 07:07 UTC, Buddhika-Pathirathna reviewed
Need to fix some broken links. Otherwise, looks good with minor changes.