Detailed events guide
casper-network/docs pull request #588
Opened 2022-07-19 17:00 UTC by Buddhika-Pathirathna

### Related links

Card - [457](https://github.com/casper-network/docs/issues/457)

### Changes

- Added the required changes 

### Notes

2022-07-21 14:49 UTC, darthsiroftardis requested changes
Some changes I would like to see

2022-07-21 14:49 UTC, darthsiroftardis commented on source/docs/casper/dapp-dev-guide/building-dapps/monitoring-events.md
> +There are three types of events in our platform categorized based on the emitting endpoint of the nodes. Those are:
```suggestion
There are three types of event streams in our platform categorized based on the emitting endpoint of the nodes. Those are:
```

2022-07-21 14:49 UTC, darthsiroftardis commented on source/docs/casper/dapp-dev-guide/building-dapps/monitoring-events.md
> +These are associated with Deploys on a node. Currently, we are handling only `DeployAccepted` event. Refer to the [Deploys](/design/execution-semantics/#execution-semantics-deploys) section to discov
```suggestion
These are associated with Deploys on a node. Currently, only `DeployAccepted` event is emitted . Refer to the [Deploys](/design/execution-semantics/#execution-semantics-deploys) section to discover more about Deploys and their life cycles.
```

2022-07-21 14:49 UTC, darthsiroftardis commented on source/docs/casper/dapp-dev-guide/building-dapps/monitoring-events.md
> +- `PORT` - The port 9999 (Since we are testing on Mainnet or Testnet)
```suggestion
- `PORT` - The port 9999 (The default port number for nodes on Mainnet or Testnet)
```

2022-07-21 14:49 UTC, darthsiroftardis commented on source/docs/casper/dapp-dev-guide/building-dapps/monitoring-events.md
> +The event stream server of the node emits this event when a Deploy has been received by the node. At this point, it needs to pass a set of validity checks. Refer to the [Deploy gossiped](/design/exec
```suggestion
The event stream server of the node emits this event when a Deploy has been received by the node. 
```
```suggestion
The event stream server of the node emits this event when a Deploy has been received by the node.
```

2022-07-21 14:49 UTC, darthsiroftardis commented on source/docs/casper/dapp-dev-guide/building-dapps/monitoring-events.md
> +You can find the definitions of the terms in the above `DeployAccepted` JSON representation by referring to the following links:
Provide a link to Deploy serialization here

2022-07-21 17:41 UTC, ACStoneCL reviewed
Some small fixes.

2022-07-21 17:41 UTC, ACStoneCL commented on source/docs/casper/dapp-dev-guide/building-dapps/monitoring-events.md
> +There are three types of events in our platform categorized based on the emitting endpoint of the nodes. Those are:
```suggestion
There are three types of event streams in our platform categorized by the emitting endpoint of the nodes. Those are:
```

2022-07-21 17:41 UTC, ACStoneCL commented on source/docs/casper/dapp-dev-guide/building-dapps/monitoring-events.md
> +These are associated with Deploys on a node. Currently, we are handling only `DeployAccepted` event. Refer to the [Deploys](/design/execution-semantics/#execution-semantics-deploys) section to discov
```suggestion
These are associated with Deploys on a node. Currently, only `DeployAccepted` events are emitted. Refer to the [Deploys](/design/execution-semantics/#execution-semantics-deploys) section to discover more about Deploys and their life cycles.
```

2022-07-21 17:41 UTC, ACStoneCL commented on source/docs/casper/dapp-dev-guide/building-dapps/monitoring-events.md
> +section to learn more about finality signature.
```suggestion
section to learn more about finality signatures.
```

2022-07-21 17:41 UTC, ACStoneCL commented on source/docs/casper/dapp-dev-guide/building-dapps/monitoring-events.md
> +The `FinalitySignature` event is emitted,  whenever a new [finality](/glossary/B/#block-finality) signature is received.
```suggestion
The `FinalitySignature` event is emitted whenever a new [finality](/glossary/B/#block-finality) signature is received.
```

2022-07-21 17:41 UTC, ACStoneCL commented on source/docs/casper/dapp-dev-guide/building-dapps/monitoring-events.md
> +- [signature](/design/serialization-standard/#signature) - A serialized bte representation of a cryptographic signature.
```suggestion
- [signature](/design/serialization-standard/#signature) - A serialized byte representation of a cryptographic signature.
```

2022-07-21 17:41 UTC, ACStoneCL commented on source/docs/casper/dapp-dev-guide/building-dapps/monitoring-events.md
> +- Refer to the [serialization standard](/design/serialization-standard/) page to get details on required custom serializations and [types](/dapp-dev-guide/sdkspec/types_chain/) page to find definitio
```suggestion
- Refer to the [serialization standard](/design/serialization-standard/) page to get details on required custom serializations and the [types](/dapp-dev-guide/sdkspec/types_chain/) page to find definitions of the terms used in the event stream output.
```

2022-07-21 17:41 UTC, ACStoneCL commented on source/docs/casper/dapp-dev-guide/building-dapps/monitoring-events.md
> +- Refer to the [serialization standard](/design/serialization-standard/) page to get details on required custom serializations and [types](/dapp-dev-guide/sdkspec/types_chain/) page to find definitio
```suggestion
- Refer to the [serialization standard](/design/serialization-standard/) page to get details on required custom serializations and the [types](/dapp-dev-guide/sdkspec/types_chain/) page to find definitions of the terms used in the event stream output.
```

2022-07-21 17:41 UTC, ACStoneCL commented on source/docs/casper/dapp-dev-guide/building-dapps/monitoring-events.md
> +- Refer to the [serialization standard](/design/serialization-standard/) page to get details on required custom serializations and [types](/dapp-dev-guide/sdkspec/types_chain/) page to find definitio
```suggestion
- Refer to the [serialization standard](/design/serialization-standard/) page to get details on required custom serializations and the [types](/dapp-dev-guide/sdkspec/types_chain/) page to find definitions of the terms used in the event stream output.
```

2022-07-25 13:17 UTC, darthsiroftardis reviewed
Another few changes, but I think they're probably the last

2022-07-25 13:17 UTC, darthsiroftardis commented on source/docs/casper/dapp-dev-guide/building-dapps/monitoring-events.md
> +Casper platform uses event streaming to notify state changes in smart contracts and nodes. A node on a Casper network streams events through the SSE (Server Sent Event) server. Events are emitted by
```suggestion
Casper platform uses event streaming to notify state changes in smart contracts and nodes. A node on a Casper network streams events through the SSE (Server Sent Event) server. Events are emitted by the event stream servers of the Casper network nodes. 
```
```suggestion
Casper platform uses event streaming to notify state changes in smart contracts and nodes. A node on a Casper network streams events through the SSE (Server Sent Event) server.
```

2022-07-25 13:17 UTC, darthsiroftardis commented on source/docs/casper/dapp-dev-guide/building-dapps/monitoring-events.md
> +The default configuration of the Casper node provides event streaming via the port specified as the `event_stream_server.address` in the node's *config.toml*, which is by default `9999` for nodes on
Lets move this line to the top of the file please

2022-07-25 13:17 UTC, darthsiroftardis commented on source/docs/casper/dapp-dev-guide/building-dapps/monitoring-events.md
> +- [Serialization Standard](/design/serialization-standard/) - Contains the details on required custom serializations.
Since we link to the deploy serialization, this line in not needed

2022-07-25 13:17 UTC, darthsiroftardis commented on source/docs/casper/dapp-dev-guide/building-dapps/monitoring-events.md
> +- Refer to the [serialization standard](/design/serialization-standard/) page to get details on required custom serializations and the [types](/dapp-dev-guide/sdkspec/types_chain/) page to find defin
Lets take this line to the top of the document, and then remove all other usages of such lines

2022-07-25 17:19 UTC, darthsiroftardis approved these changes

2022-07-25 17:24 UTC, merged