Added content describing difference between session and contract code
casper-network/docs pull request #666
Opened 2022-09-01 11:01 UTC by GloreenS

### Related links

Card #609

2022-09-01 14:18 UTC, ACStoneCL approved these changes
I think the content here is good, my only suggestion would be to place it between "Unit Testing Session Code" and "Writing a Basic Smart Contract in Rust" in the sidebar.

I think using it as a delineator between the Session Code docs and the Contract Code docs would help get the idea across.

2022-09-06 15:14 UTC, ipopescu commented
@Shalmali123 @ramujin please take a look as well.

2022-09-07 09:54 UTC, ipopescu requested changes
@GloreenS @darthsiroftardis @ACStoneCL I am requesting changes because I am concerned about the use of the key management contract here. Please review, and perhaps a different contract can be used until the key management contract can be published again. 
Second, there is a duplicate section in the docs that needs to be updated.

2022-09-07 09:54 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/writing-contracts/session-contract-diff.md
> +| Session code always executes in the context of the account that signed the deploy that contains the session code. | Contract code executes within the context of its own state. |
@GloreenS @ACStoneCL can we add a bit more detail here explaining what a contract's state is? Maybe something like this:
```suggestion
| Session code always executes in the context of the account that signed the deploy that contains the session code. | Contract code executes within the context of its own state, meaning the contract's abstract environment containing [named keys](/dapp-dev-guide/sdkspec/types_chain/#namedkey). |
```

2022-09-07 09:54 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/writing-contracts/session-contract-diff.md
> +| When a `put_key` call is made within the body of the session code, the key is added to the account's named keys.| When `put_key` call is made within the contract's execution, the key is inserted in
Small typo
```suggestion
| When a `put_key` call is made within the body of the session code, the key is added to the account's named keys.| When a `put_key` call is made within the contract's execution, the key is inserted into the contract's context. So, the key will appear in the contract's named keys.|
```

2022-09-07 09:54 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/writing-contracts/session-contract-diff.md
> +This session code issues a delegation request to a pre-installed system contract. It accepts a delegator's public key, validator's public key, amount and a delegation rate and issues a delegation req
```suggestion
This session code issues a delegation request to a pre-installed system contract. It accepts a delegator's public key, a validator's public key, the amount to delegate, and a delegation rate. It then issues a delegation request to the auction contract. 
```

2022-09-07 09:54 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/writing-contracts/session-contract-diff.md
> +This contract code helps with key management. The various entry points such as `set_key_weight`, `set_deployment_threshold`, and `set_key_management_threshold` allow  you to interact with the contrac
@darthsiroftardis, I thought we said that we would not include key management contract code in the documentation until the code gets revisited. 
@GloreenS @darthsiroftardis please revisit this code and perhaps include another example contract, such as a snippet from the NFT contract.

2022-09-14 14:07 UTC, darthsiroftardis requested changes
Lets remove all code samples from this page and just focus on the informational content

2022-09-14 16:41 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/writing-contracts/session-contract-diff.md
> +| When a `put_key` call is made within the body of the session code, the key is added to the account's named keys.| When `put_key` call is made within the contract's execution, the key is inserted in
I see Gloreen applied the change. Resolving the conversation.

2022-09-14 16:41 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/writing-contracts/session-contract-diff.md
> +This contract code helps with key management. The various entry points such as `set_key_weight`, `set_deployment_threshold`, and `set_key_management_threshold` allow  you to interact with the contrac
Code was removed.

2022-09-14 16:45 UTC, ipopescu commented
> @GloreenS are you planning to keep this section as well: https://docs.casperlabs.io/dapp-dev-guide/writing-contracts/session-code/#comparing-session-code-and-contract-code. I recommend removing it as it is a duplicate, or you can link to the new page created.

This is the only comment that I have remaining. All others have been resolved. Thank you!

2022-09-19 13:45 UTC, darthsiroftardis approved these changes

2022-09-19 13:57 UTC, ipopescu approved these changes

2022-09-19 13:57 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/writing-contracts/session-code.md
> +To understand the difference between session code and contract code, see [Difference Between Session Code and Smart Contract](../writing-contracts/rust.md/#difference-between-session-code-and-smart-c
```suggestion
To understand the difference between session code and contract code, see [Difference Between Session Code and Smart Contract](../writing-contracts/rust.md/#difference-between-session-code-and-smart-contract).
```

2022-09-19 14:41 UTC, merged