Adding links to chainspec file and gas limit details
casper-network/docs pull request #673
Opened 2022-09-05 09:18 UTC by Buddhika-Pathirathna

### Related links

Related card - [634](https://github.com/casper-network/docs/issues/634)

### Changes
- Added the link to the chainspec file in the Glossary definition
- link the glossary definition to the 'chainspec' word occurrences
- Added the link to the gas limit in required occurances

### Notes

2022-09-07 12:18 UTC, ipopescu requested changes
Requesting a technical review from @darthsiroftardis. I think it's worth being exact about the wording and should be a quick check. Thanks!

2022-09-07 12:18 UTC, ipopescu commented on source/docs/casper/design/execution-semantics.md
> +Computation is all done in a [WebAssembly (wasm)](https://webassembly.org/) interpreter, allowing any programming language which compiles to wasm to become a smart contract language for the Casper bl
Here we are pointing to the block gas limit, which may not be the same. Do we need to reword this to say: "All executions are finite because each block has a finite gas limit", @darthsiroftardis? 
```suggestion
Computation is all done in a [WebAssembly (wasm)](https://webassembly.org/) interpreter, allowing any programming language which compiles to wasm to become a smart contract language for the Casper blockchain. Similar to Ethereum, we use [`Gas`](/economics/gas-concepts/) to measure computational work in a way which is consistent from node to node in the Casper Network. Each wasm instruction is [assigned](https://github.com/casper-network/casper-node/blob/cb1d20ad1ea6e245cd8237f9406885a1e785c669/execution_engine/src/shared/wasm_config.rs#L15) a `Gas` value, and the amount of gas spent is tracked by the runtime with each instruction executed by the interpreter. All executions are finite because each block has a finite [_gas limit_](https://github.com/casper-network/casper-node/blob/b94c4f79ac4ca00e996c418dcc3a98607779a193/resources/production/chainspec.toml#L96-L97) that specifies the maximum amount of gas that can be spent per block before the computation is terminated by the runtime. How this limit is determined is discussed in more detail below.
```

2022-09-07 12:18 UTC, ipopescu commented on source/docs/casper/economics/gas-concepts.md
> +When a smart contract hits its [gas limit](https://github.com/casper-network/casper-node/blob/b94c4f79ac4ca00e996c418dcc3a98607779a193/resources/production/chainspec.toml#L96-L97) (the payment amount
This is the block gas limit, not the contract's gas limit. Before changing this, we need a review from @darthsiroftardis.

2022-09-07 12:18 UTC, ipopescu commented on source/docs/casper/economics/runtime.md
> +The [block gas limit](https://github.com/casper-network/casper-node/blob/b94c4f79ac4ca00e996c418dcc3a98607779a193/resources/production/chainspec.toml#L96-L97) is split into two lanes, one for native
This is good here.

2022-09-07 12:18 UTC, ipopescu commented on source/docs/casper/glossary/C.md
> +A collection of configuration settings describing the state of the system at genesis and upgrades to basic system functionality (including system contracts and gas costs) occurring after [genesis](G.
```suggestion
A collection of configuration settings describing the state of the system at genesis and upgrades to basic system functionality (including system contracts and gas costs) occurring after [genesis](G.md#genesis). Here is an example [chainspec](https://github.com/casper-network/casper-node/blob/release-1.4.8/resources/production/chainspec.toml), which will change with newer releases.
```

2022-09-07 12:18 UTC, ipopescu commented on source/docs/casper/operators/create.md
> +A version of the [chainspec](https://github.com/casper-network/casper-node/blob/release-1.4.8/resources/production/chainspec.toml) is downloaded by the `pull_casper_node_version.sh` script installed
Here you can point to the glossary so that the chainspec example is updated in a single location (the one from the glossary).

2022-09-14 14:27 UTC, darthsiroftardis commented on source/docs/casper/design/execution-semantics.md
> +Computation is all done in a [WebAssembly (wasm)](https://webassembly.org/) interpreter, allowing any programming language which compiles to wasm to become a smart contract language for the Casper bl
Okay, so there is a block gas limit, but the payment amount specified within the deploy structure determines the the gas limit for execution. How much gas you're willing to pay is the limit, if this section is point to the block gas limit, then we should change it to not point there

2022-09-14 14:30 UTC, darthsiroftardis commented on source/docs/casper/economics/gas-concepts.md
> +The amount of gas required for a transaction is determined by how much code is executed on the blockchain. Usually, the platform defines the required gas limit for a Deploy, inside a block through a
This sounds incorrect, the deploy sender sets the gas price which is shown in the deploy header structure, the only upper limit of gas is the block gas limit itself, and the information in the parentheses is just dead wrong, unless I am reading it wrong 1 CSPR is 10^9 motes, not the other way around

2022-09-14 14:32 UTC, darthsiroftardis reviewed
Some corrections are needed before this PR can be approved

2022-09-14 14:32 UTC, darthsiroftardis commented on source/docs/casper/economics/gas-concepts.md
> +When a smart contract hits its [gas limit](https://github.com/casper-network/casper-node/blob/b94c4f79ac4ca00e996c418dcc3a98607779a193/resources/production/chainspec.toml#L96-L97) (the payment amount
@ipopescu You are correct, these links are pointing to the block gas limit which is very different from what is being spoken about in this paragraph

2022-09-14 16:57 UTC, ipopescu commented on source/docs/casper/design/execution-semantics.md
> +Computation is all done in a [WebAssembly (wasm)](https://webassembly.org/) interpreter, allowing any programming language which compiles to wasm to become a smart contract language for the Casper bl
Understood. So @Buddhika-Pathirathna there are 2 solutions here:
1) remove the link
2) remove the link and add a short additional explanation, which would clarify that the payment amount specified within the deploy sets the gas limit for deploy execution. 
I prefer option 2 since I was confused here :).

2022-09-14 16:58 UTC, ipopescu commented on source/docs/casper/economics/gas-concepts.md
> +When a smart contract hits its [gas limit](https://github.com/casper-network/casper-node/blob/b94c4f79ac4ca00e996c418dcc3a98607779a193/resources/production/chainspec.toml#L96-L97) (the payment amount
Ok let's remove the link here and go back to what we had before @Buddhika-Pathirathna.

2022-09-14 17:07 UTC, ipopescu commented on source/docs/casper/economics/gas-concepts.md
> +The amount of gas required for a transaction is determined by how much code is executed on the blockchain. Usually, the platform defines the required gas limit for a Deploy, inside a block through a
There should be a negative sign there. Or we should say in brackets (1 CSPR is 10^9 motes). Let's remove the link and update the information about motes:
```suggestion
The amount of gas required for a transaction is determined by how much code is executed on the blockchain. Currently, gas is priced at a fixed price of 1 mote (1 CSPR is 10^9 motes) per 1 unit of gas. The gas charged for a transaction on the blockchain is paid to the network's validators.
```

2022-09-14 17:08 UTC, ipopescu commented
@Buddhika-Pathirathna Let's use the link to the chainspec in the glossary. Please ping me when the PR is ready for another review pass. Thank you!

2022-09-23 11:18 UTC, ipopescu approved these changes
LGTM, @Buddhika-Pathirathna! Please merge when you can.

2022-09-23 11:30 UTC, merged