Update getting-started.md
casper-network/docs pull request #690
Opened 2022-09-16 20:47 UTC by ipopescu

The video list changed, so we are showing the wrong video for this section. I found this while reading the docs.

2022-09-17 22:48 UTC, ramujin requested changes
The contract upgrades link is still incorrect. I left a comment with the correct link, but the others are pointing to the right videos for me now.

2022-09-17 22:48 UTC, ramujin commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +<iframe width="560" height="315" src="https://www.youtube.com/embed?v=Q4ZXNV8EVTk&list=PL8oWxbJ-csEogSV-M0IPiofWP5I_dLji6&index=6" frameborder="0" allow="accelerometer; autoplay; clipboard-write; enc
This link points to the "getting started with casper smart contracts" video because you linked the playlist instead of the individual one, and that one is the first of 4 videos in the playlist. I believe this is the correct link: https://www.youtube.com/embed?v=Q4ZXNV8EVTk&list=PL8oWxbJ-csEogSV-M0IPiofWP5I_dLji6&index=4

2022-09-17 23:53 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +<iframe width="560" height="315" src="https://www.youtube.com/embed?v=Q4ZXNV8EVTk&list=PL8oWxbJ-csEogSV-M0IPiofWP5I_dLji6&index=6" frameborder="0" allow="accelerometer; autoplay; clipboard-write; enc
I also tried the link you suggested initially, and when I embed it, I get an error on my local instance (first screenshot below). But index=6 works because there are 2 hidden videos (second screenshot). I can try to clean up the playlist instead, but I am not sure it will solve the problem.

<img width="957" alt="Screen Shot 2022-09-18 at 1 48 33 AM" src="https://user-images.githubusercontent.com/4185994/190879947-664b1587-bfeb-4549-a56d-e3190c6f3969.png">
<img width="1129" alt="Screen Shot 2022-09-18 at 1 50 16 AM" src="https://user-images.githubusercontent.com/4185994/190879948-0bf9a157-6a6e-4019-944a-1af471b231b9.png">

2022-09-17 23:57 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +<iframe width="560" height="315" src="https://www.youtube.com/embed?v=Q4ZXNV8EVTk&list=PL8oWxbJ-csEogSV-M0IPiofWP5I_dLji6&index=6" frameborder="0" allow="accelerometer; autoplay; clipboard-write; enc
@ramujin I was able to clean up the playlist and removed the 2 deleted videos from it. Now the link you suggested works, and I have updated it. Thanks!

2022-09-17 23:59 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +<iframe width="560" height="315" src="https://www.youtube.com/embed?v=Q4ZXNV8EVTk&list=PL8oWxbJ-csEogSV-M0IPiofWP5I_dLji6&index=4" frameborder="0" allow="accelerometer; autoplay; clipboard-write; enc
<img width="1169" alt="Screen Shot 2022-09-18 at 1 58 50 AM" src="https://user-images.githubusercontent.com/4185994/190880044-3f4f5b26-a9c9-4800-b6b5-3b6be82af764.png">

2022-09-18 06:33 UTC, ramujin approved these changes
Looks great now! Thanks for fixing it.

2022-09-18 11:23 UTC, merged