Bradjohnl rem stag site
casper-network/docs pull request #807
Opened 2022-12-09 15:45 UTC by bradjohnl

This PR implements the discussed changes:
- Remove the staging deployment.
- Start prod deployments directly when PRs are merged to dev
- Remove the PR-bot app and logic.

It also improves existing actions that are being migrated to Node v16 from v12.

2022-12-09 17:05 UTC, ipopescu commented
@bradjohnl Looking at the patterns, they look ok to me, but I don't fully understand the changes. Should we get Tom to approve them? Or is there a way to test them?

2022-12-09 18:19 UTC, TomVasile requested changes
just some nit picks about using commit sha's

2022-12-09 18:19 UTC, TomVasile commented on .github/workflows/main.yml
> +      - uses: actions/upload-artifact@v3
best practices from github on using actions is to pin to a specific sha hash

https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

2022-12-09 18:19 UTC, TomVasile commented on .github/workflows/main.yml
> +        uses: actions/setup-node@v3
same deal

2022-12-09 18:19 UTC, TomVasile commented on .github/workflows/main.yml
> +      - uses: actions/upload-artifact@v3
same deal

2022-12-12 19:10 UTC, TomVasile commented on .github/workflows/main.yml
> +      - uses: actions/upload-artifact@v3
fair, i'll approve

2022-12-12 19:10 UTC, TomVasile approved these changes

2022-12-13 11:23 UTC, merged