Templates
casper-network/docs pull request #856
Opened 2023-01-20 17:21 UTC by ioreka

### Changes

This PR adds 2 template ideas, for further review/refinement by the Casper team. They are for Casper internal and external users to follow (optionally) to ensure that contributions from eg. the community are consistent with internal team contributions.

### Notes

- At the moment, they're in `.github/templates` because I wasn't sure where else to put them - they aren't necessarily required to live there, because there's no CICD or automated process that GH runs and uses them, and also it means they will be "hidden", but just putting them in there right now because it was literally called "Templates". TBC where they should live, maybe in a contrib folder and linked out to in the contrib docs
- If user needs dictate, more templates could be added in future

2023-02-03 15:48 UTC, ACStoneCL requested changes
Just one note and two (1.5? Not sure about the code snippet issue.) corrections.

2023-02-03 15:48 UTC, ACStoneCL commented on .github/templates/tutorial-template.md
> +<!-- If you need any help, tag our developer advocates (info here) or TW team (info here). Thank you for contributing! -->
We'll need to determine contact links for dev advocates/tech writers when we begin using this template extensively.

As is, I think it's okay to leave it like this until those determinations take place.

2023-02-03 15:48 UTC, ACStoneCL commented on .github/templates/tutorial-template.md
> +Give a high-level overview of the tutorial. This helps the reader understand the scope of what they'll be doing e2e and potentially the basic architecture of what will speak to/interact with what.
```suggestion
Give a high-level overview of the tutorial. This helps the reader understand the scope of what they'll be doing end-to-end and potentially the basic architecture of what will speak to/interact with what.
```

2023-02-03 15:48 UTC, ACStoneCL commented on .github/templates/tutorial-template.md
> +### Single or multi-page?
It might just be a quirk of the Github review window, but for some reason the code snippet above is including the "Single or multi-page" subsection.

I checked in VS Code and the 'Edit File' window, and I don't seem to be getting the same issue.

2023-02-03 17:40 UTC, ipopescu requested changes
@ioreka, thank you for the work! I am requesting a few minor updates.

Also, the following 2 files need to be updated once templates become available:

- https://github.com/casper-network/docs/blob/dev/README.md
- /docs/source/docs/casper/workflow/contribute.md

Also, I’ve had in mind to move the contribute.md file on the same level as the README, not hurried in the workflow folder. See https://github.com/casper-network/docs/issues/871.

2023-02-03 17:40 UTC, ipopescu commented on .github/templates/overview-template.md
> +<!-- It can be used at any nested level in the docs where there is an "Overview" page. Delete any sections you feel aren't relevant. -->
Let's specify when an overview is needed: to tie multiple topics together in a subsection of the docs.

2023-02-03 17:40 UTC, ipopescu commented on .github/templates/overview-template.md
> +## Quick links
We usually capitalize all words in first and second-level headers. If we want to change this, the docs need to be updated.

```suggestion
## Quick Links
```

2023-02-03 17:40 UTC, ipopescu commented on .github/templates/overview-template.md
> +## Related links
I would keep only one section with links, for simplicity, and remove this second "Related Links" section.

2023-02-03 17:40 UTC, ipopescu commented on .github/templates/tutorial-template.md
> +# Tutorial title
We capitalize all words in level 1 (#) and level 2 (##) headers. If you'd like to change this, we need to agree and update all the headers in the docs.

2023-02-03 17:40 UTC, ipopescu commented on .github/templates/tutorial-template.md
> +If relevant, include what they'll have achieved or built "by the end of this tutorial."
I think we can remove the quotation marks.
```suggestion
If relevant, include what they'll have achieved or built by the end of this tutorial.
```

2023-02-03 17:40 UTC, ipopescu commented on .github/templates/tutorial-template.md
> +## Pre-requisites
```suggestion
## Prerequisites
```

2023-02-03 17:40 UTC, ipopescu commented on .github/templates/tutorial-template.md
> +This can incluce:
```suggestion
This can include:
```

2023-02-03 17:40 UTC, ipopescu commented on .github/templates/tutorial-template.md
> +- [ ] Anything else that if relevant
```suggestion
- [ ] Anything else that is relevant
```

2023-02-03 17:40 UTC, ipopescu commented on .github/templates/tutorial-template.md
> +Advice on common gotchas or specific error messages that might pop up, or the support route if the user needs help.
I suggest removing slang words
```suggestion
Advice on common questions or specific error messages that might pop up or the support route if the user needs help.
```

2023-02-03 17:40 UTC, ipopescu commented on .github/templates/tutorial-template.md
> +Further tutorials or docs to check out, once someone has successfully completed your tutorial.
Use "read" or "look at" instead of "check out". It's a little more formal.
```suggestion
Further tutorials or docs to read once someone has successfully completed your tutorial.
```

2023-02-03 17:40 UTC, ipopescu commented on .github/templates/tutorial-template.md
> +### Troubleshooting
It might be good to have this a level higher, as it's not part of the "steps".
```suggestion
## Troubleshooting
```

2023-02-03 17:40 UTC, ipopescu commented on .github/templates/tutorial-template.md
> +### Post-tutorial
Maybe we can call this Next Steps or something different, and move it a level higher.
```suggestion
##  Next Steps
```

2023-02-03 17:40 UTC, ipopescu commented on .github/templates/tutorial-template.md
> +## Things to remember
```suggestion
## Things to Remember
```

2023-02-03 17:40 UTC, ipopescu commented on .github/templates/tutorial-template.md
> +### Single or multi-page?
```suggestion
### Single or multi-page tutorial?
```

2023-02-03 18:01 UTC, ioreka commented on .github/templates/tutorial-template.md
> +# Tutorial title
Oh no that's my mistake - apologies

2023-02-03 18:08 UTC, ioreka commented on .github/templates/tutorial-template.md
> +### Single or multi-page?
hmmm ok.. it #looksFineOnMyMachine in VSCode and local docs but let me know if it renders badly on the actual docs when in prod 
<img width="757" alt="image" src="https://user-images.githubusercontent.com/38460768/216675792-8eead288-dd85-414a-ac9b-34578c4474ec.png">

2023-02-03 18:23 UTC, ioreka commented
@ipopescu thanks for the comment re: the additional files to be updated, i'll get to that first thing on Monday. have a great weekend!

2023-02-06 11:55 UTC, ioreka commented
@ipopescu thanks for the file names. I've added links pointing to where the templates should end up into those 2 files

2023-02-06 14:56 UTC, ipopescu approved these changes
I added a few minor nits, otherwise, it LGTM!

2023-02-06 14:56 UTC, ipopescu commented on .github/templates/overview-template.md
> +<!-- An "Overview" page is used to tie multiple topics together in a subsection of the docs. -->
```suggestion
<!-- An "Overview" page ties multiple topics together in a subsection of the docs. -->
```

2023-02-06 14:56 UTC, ipopescu commented on .github/templates/overview-template.md
> +Users might already know where they want to go. To save time, include a list here to popular pages.
```suggestion
Users might already know where they want to go. To save time, include a list here of popular pages.
```

2023-02-06 14:56 UTC, ipopescu commented on .github/templates/tutorial-template.md
> +<!-- However, feel free to delete anything that isn't relevant to your tutorial.  -->
```suggestion
<!-- However, feel free to delete anything irrelevant to your tutorial.  -->
```

2023-02-06 14:56 UTC, ipopescu commented on .github/templates/tutorial-template.md
> +Remember to add the language when including any code blocks. While not supported natively by markdown, many markdown engines (including the one used by GitHub) will support syntax highlighting which
```suggestion
Remember to add the language when including any code blocks. While not supported natively by markdown, many markdown engines (including the one used by GitHub) will support syntax highlighting, which is helpful for reviewers and future maintainers of your tutorial:
```

2023-02-06 15:07 UTC, ipopescu commented on source/docs/casper/workflow/contribute.md
> +* [Tutorial page](https://github.com/casper-network/docs/tree/dev/.github/templates/tutorial-template.md)
@ioreka looks like these links are failing the build because the files don't exist yet. So, maybe we need to specify them as relative. From the workflow folder, they would look like this:

- ../../../../.github/templates/overview-template.md
- ../../../../.github/templates/tutorial-template.md

I will give it a try to fix these with a commit.

2023-02-06 16:59 UTC, ACStoneCL approved these changes
LGTM, approving based on merge occurring after addressing @ipopescu 's suggestions.

2023-02-06 19:10 UTC, ipopescu approved these changes
Re-approving after fixing the build. @ioreka, please address the other small suggestions before merging. Thanks!

2023-02-07 18:16 UTC, ioreka commented
updated, i don't have write access to the repo though, would one of you mind merging when the CI tests pass? thank you

2023-02-07 18:26 UTC, merged