Restructure prototype
casper-network/docs pull request #912
Opened 2023-02-21 16:33 UTC by andrzej-casper

2023-02-22 23:05 UTC, andrzej-casper commented
As requested for this PR during today's mob review:

1. How To's index removed.
2. dapp-dev-guide/building-dapps/calling-contracts placed under "Writing On-Chain Code".
3. Announcement bar added:

![announcement](https://user-images.githubusercontent.com/121791569/220782710-46a82b20-f840-4919-80ea-6a724a988bbd.png)

@darthsiroftardis @ipopescu Let's light this candle! :rocket:

2023-02-23 15:11 UTC, ipopescu requested changes
Thanks @andrzej-casper for the thorough work and explanation.
I have left several requests before merging this PR to the live site.

Also, 3 pages with “table of contents” do not list the contents correctly according to the new structure. I wasn’t able to leave a comment for the users/index.md page that needs to be updated to match the new structure.
- /developers/table-of-content/ 
- /operators/table-of-content/ 
- /users/ 

TODOs post-merge. FYI @Adrian-Wrona.

As discussed, we need to review and revise the order in the left navigation bar. Also, several inconsistencies exist in the new headings introduced (Introduction, Overview, Table of Contents). Ideally, this would all be sorted before the content is pushed live, but we can address it asap afterward.

Also, I am not sure why these are rendered with the incorrect case in the new structure:
	Interacting with the Blockchain Using CLI
	Becoming a Validator
	Setting Up a Network
It is not a PR blocker but needs to be fixed after this PR. 

I found a few inconsistent titles that need to be updated later (from the old content):
Setting Up a Private Casper Network to match the other titles
Block Explorers on Casper Network => Block Explorers for Casper Networks

I also saw this incorrectly rendered note while reviewing, but I don’t want to update until this PR merges.

::note
Please make sure you are running this tool as the same user that owns $DATA_DIR. Otherwise, you may receive a permission denied error.
:::

2023-02-23 15:11 UTC, ipopescu commented on source/docs/casper/developers/table-of-content.md
> +- [Using the Casper Fungible Token Contract](https://github.com/casper-network/erc20-guide-extraction/): using the Casper fungible token contract to understand the fungible token transfer workflow
The content listed here doesn’t match the new structure. Please update.

2023-02-23 15:11 UTC, ipopescu commented on source/docs/casper/operators/table-of-content.md
> +- [How to Stage Files for a New Network](./setup-network/staging-files-for-new-network.md): a guide to hosting protocol files for a new Casper network
The content listed here doesn’t match the new structure. Please update.

2023-02-23 15:15 UTC, ipopescu commented on config/sidebar.config.js
> +            label: "Why Build on Casper",
This needs to be done as part of this PR.

2023-02-23 15:15 UTC, ipopescu commented on source/docs/casper/operators/table-of-content.md
> +- [How to Stage Files for a New Network](./setup-network/staging-files-for-new-network.md): a guide to hosting protocol files for a new Casper network
Please do the same for the users table of contents.

2023-02-24 14:27 UTC, andrzej-casper commented on config/navbar.config.js
> +            to: `${routePrefix}/users`,
Fixed in https://github.com/casper-network/docs/pull/912/commits/0d21967d94cd7253ed79cf8577721282a6e8cfaa.

2023-02-24 14:28 UTC, andrzej-casper commented on config/sidebar.config.js
> +        //        //                },
Task tracked internally as `CAS-64`.

2023-02-24 14:33 UTC, andrzej-casper commented on source/docs/casper/developers/cli/index.md
> +# Overview
Further discussion is required - task tracked internally as `CAS-65`.

2023-02-24 14:34 UTC, andrzej-casper commented on source/docs/casper/resources/tutorials/index.md
> +
Task tracked internally as `CAS-60`.

2023-02-24 14:48 UTC, andrzej-casper commented on config/sidebar.config.js
> +            label: "Interacting with the Blockchain using CLI",
This is the default behavior of Docusaurus - it uses uppercase for all collapsible items. This applies to https://docs.casperlabs.io/ as well:

![image](https://user-images.githubusercontent.com/121791569/221207213-fc254d7f-0945-4d7c-b14a-604a89d81f19.png)

If you think case should not be transformed, please create relevant issue and let me know. I can provide simple CSS workaround for it :wink:.

2023-02-27 09:28 UTC, andrzej-casper commented on config/announcement.config.js
> +    content: "Documentation is undergoing changes for our new <b>Developer Portal</b> launching in Q1. Please excuse any disruptions.",
Updated.

2023-02-27 09:29 UTC, andrzej-casper commented on config/sidebar.config.js
> +            label: "Build dApps",
Suggestion approved.

2023-02-27 09:33 UTC, andrzej-casper commented on config/sidebar.config.js
> +        "operators/table-of-content",
Fixed in https://github.com/casper-network/docs/pull/912/commits/00c0e8931de8b0f6881587fd89c1212dce8ebdde.

2023-02-27 09:37 UTC, andrzej-casper commented on config/sidebar.config.js
> +                            label: "Build Counter on the Testnet",
Original title restored in https://github.com/casper-network/docs/pull/912/commits/f79f01fbadd730252b0e29bd674f946b234fa47d.

2023-02-27 09:37 UTC, andrzej-casper commented on config/sidebar.config.js
> +                            label: "Build Counter on an NCTL Network",
Original title restored in https://github.com/casper-network/docs/pull/912/commits/f79f01fbadd730252b0e29bd674f946b234fa47d.

2023-02-27 09:51 UTC, andrzej-casper commented on config/sidebar.config.js
> +            label: "Why Build on Casper",
Moved in https://github.com/casper-network/docs/pull/912/commits/291d05016363b52ee3f4dfa734f09fd55475acee.

2023-02-27 10:24 UTC, andrzej-casper commented on source/docs/casper/developers/table-of-content.md
> +- [Using the Casper Fungible Token Contract](https://github.com/casper-network/erc20-guide-extraction/): using the Casper fungible token contract to understand the fungible token transfer workflow
Done in https://github.com/casper-network/docs/pull/912/commits/e42c0c5239cc3cc2a6f7f68e6716b2e46326cd18.

2023-02-27 10:24 UTC, andrzej-casper commented on source/docs/casper/operators/table-of-content.md
> +- [How to Stage Files for a New Network](./setup-network/staging-files-for-new-network.md): a guide to hosting protocol files for a new Casper network
Done in https://github.com/casper-network/docs/pull/912/commits/e42c0c5239cc3cc2a6f7f68e6716b2e46326cd18.

2023-02-27 10:27 UTC, andrzej-casper commented
@ipopescu All changes requested for this PR were addressed, branch rebased to latest dev.

:fireworks: New live demo: https://bucolic-zuccutto-8f268c.netlify.app/.

2023-02-27 16:57 UTC, ipopescu commented on config/sidebar.config.js
> +            label: "Interacting with the Blockchain using CLI",
Opened issue https://github.com/casper-network/docs/issues/933 to track this.

2023-02-27 16:58 UTC, ipopescu commented on source/docs/casper/developers/table-of-content.md
> +- [Using the Casper Fungible Token Contract](https://github.com/casper-network/erc20-guide-extraction/): using the Casper fungible token contract to understand the fungible token transfer workflow
I submitted additional commits regarding this.

2023-02-27 16:58 UTC, ipopescu commented on source/docs/casper/operators/table-of-content.md
> +- [How to Stage Files for a New Network](./setup-network/staging-files-for-new-network.md): a guide to hosting protocol files for a new Casper network
I submitted additional commits regarding this.

2023-02-27 19:39 UTC, darthsiroftardis commented
My only concern currently is that we need to surface the serialization standard to a higher level. If we can figure that, I can approve the PR

2023-02-28 08:16 UTC, ipopescu commented
As discussed, we won't standup a feature branch for this PR but a staging environment.

2023-02-28 11:35 UTC, andrzej-casper commented
@ipopescu I went through your commits, great work! Here is the latest live demo that includes your changes: https://deft-croissant-d02536.netlify.app/.

2023-02-28 12:09 UTC, andrzej-casper commented
@darthsiroftardis What about moving it one layer up?

![image](https://user-images.githubusercontent.com/121791569/221848824-a6758847-39e6-41c7-ad9c-0d00745cb89d.png)

To be honest, I would prefer to resolve those small issues later. The purpose of this PR was to get prototype of new structure **ASAP**, so we can avoid double work - until then we are forced to work on [doc](https://github.com/casper-network/docs-new). Every change on your `dev` branch will cause conflicts to resolve here, so in some way it is also blocker for you.

2023-02-28 12:20 UTC, andrzej-casper commented
@ipopescu @darthsiroftardis One additional question regarding _staging server_. Is the idea here to setup CI/CD deploying **every** branch in this repository, to have live preview out of the box?

2023-02-28 15:49 UTC, andrzej-casper commented
@darthsiroftardis I moved serialization page as suggested.

2023-02-28 17:32 UTC, darthsiroftardis approved these changes
Approved, however, subsequent PRs should be targeting the feat branch

2023-02-28 17:41 UTC, merged

2023-02-28 17:45 UTC, andrzej-casper commented
> Approved, however, subsequent PRs should be targeting the feat branch

@darthsiroftardis I see no reason in using feature branch. We need to have discussion, because it seems we are going in circles.

2023-07-12 10:00 UTC, andrzej-casper commented on config/sidebar.config.js
> +            label: "Interacting with the Blockchain using CLI",
Fixed in https://github.com/casper-network/docs/pull/960.

2023-07-12 10:01 UTC, andrzej-casper commented on config/sidebar.config.js
> +        //        //                },
Fixed in https://github.com/casper-network/docs/pull/958.