Updated the upgrade tutorial
casper-network/docs pull request #935
Opened 2023-02-28 15:15 UTC by ShalmaliCL

Updated the upgrade documentation to use the new counter

### What does this PR fix/introduce?
- Updated upgrade flow with new counter details
- Added commands and the context wherever required.

### Checklist
(Delete any that aren't relevant)

- [ ] I ran the docs locally using `yarn install` and `yarn run start`.
- [ ] My changes follow the [Casper docs style guidelines](https://docs.casperlabs.io/workflow/contribute/).
- [ ] All links (internal and external) have been verified.
- [ ] All technical procedures have been tested (if you want help with this, mention it in [Reviewers](#reviewers)).
- [ ] If structural changes are introduced (not just content changes), cross-browser testing has been completed.

### Reviewers
@ipopescu and @ACStoneCL

2023-02-28 16:32 UTC, ACStoneCL requested changes
A few change requests for flow and clarity.

2023-02-28 16:32 UTC, ACStoneCL commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +- contract-v2 is the contract with the new entry point called counter_decrement.
```suggestion
- contract-v2 is the contract with the new entry point called `counter_decrement`.
```

This is just a suggestion, it might make the entry point name more clear.

2023-02-28 16:32 UTC, ACStoneCL commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +Prerequisite for the below commands is that you have already installed the contract-v1 as shown in the [counter tutorial](/dapp-dev-guide/tutorials/counter-testnet) before you install the contract-v2
```suggestion
Installing contract-v1 as shown in the [counter tutorial](/dapp-dev-guide/tutorials/counter-testnet) is a prerequisite before installing contract-v2.
```

2023-02-28 16:32 UTC, ACStoneCL commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +Now, let's deploy version 2 of the contract, which will add the counter_decrement entry point to an existing contract package on the chain.
```suggestion
Now, let's deploy version 2 of the contract, which will add the `counter_decrement` entry point to an existing contract package on the chain.
```

Same as above, just a suggestion.

2023-02-28 16:32 UTC, ACStoneCL commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +If you run below commands, you will be able to observe the new contract entry points.
```suggestion
Running the below commands will allow you to observe the new contract entry points.
```

2023-02-28 16:32 UTC, ACStoneCL commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +Let’s check the new contract entry points. You should see the _counter_decrement_ entry point now.
```suggestion
Check the new contract entry points. You should see the _counter_decrement_ entry point now.
```

I think we can remove 'Let's' from before these explanations.

2023-02-28 16:32 UTC, ACStoneCL commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +Let's check the version and package details with the latest state root hash:
```suggestion
Check the version and package details with the latest state root hash:
```

2023-02-28 16:32 UTC, ACStoneCL commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +Now let’s exercise the new entry point and check the results. The below command will call the _counter_decrement_ entry point using package name.
```suggestion
Call the new entry point and check the results. The below command will call the _counter_decrement_ entry point using package name.
```

2023-02-28 16:32 UTC, ACStoneCL commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +- To call the entry point we wish to access, the contract version number, and any runtime arguments. The call defaults to the highest enabled version if no version was specified.
```suggestion
- Calling the contract by package hash requires the entry point we wish to access, the contract version number, and any runtime arguments. The call defaults to the highest enabled version if no version was specified. 
```

2023-02-28 16:32 UTC, ACStoneCL commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +- To call an entry point in a contract by referencing the contract package name, you can use the session-package-name and session-entry-point.
```suggestion
- Calling the contract by its contract package name requires the session-package-name and session-entry-point. 
```

2023-02-28 16:32 UTC, ACStoneCL commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +- This will enable you to access the entry-point in global state by using the put-deploy command. You will find stored the "contract_package_name" into a NamedKey, which we can use in the code.
```suggestion
- This will enable you to access the entry-point in global state by using the put-deploy command. The "contract_package_name" will be stored in a NamedKey in the account's context.
```

2023-02-28 16:32 UTC, ACStoneCL commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +After calling the entry-point, the count value should decrement by one. You can query the network again, however, remember that you have to get a new state root hash. Check if the count was decrement
```suggestion
After calling the entry-point, the count value should decrement by one. You can verify the decrement by querying the network again, but you will need a new state root hash.
```

2023-02-28 16:41 UTC, ShalmaliCL commented
@ACStoneCL - I have incorporated the suggested changes.

2023-02-28 19:33 UTC, ipopescu requested changes
@ShalmaliCL, I’ve added my feedback as well. In addition, please fix the broken links and merge conflicts before re-submitting for a final review.
Also, note that the content we had for training needs to be formatted differently and merged with the existing written content in this tutorial.

2023-02-28 19:33 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +In this tutorial, we will be using [version two of the example counter contract](https://github.com/casper-ecosystem/counter/blob/master/contract-v2/src/main.rs) to demonstrate the upgraded workflow.
```suggestion
In this tutorial, you will use [the second version](https://github.com/casper-ecosystem/counter/blob/master/contract-v2/src/main.rs) of the counter contract to perform the upgrade.
```

2023-02-28 19:33 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
>  5. Verify that your new contract version works as desired
After listing these steps, link somehow to the first version of the counter contract as an example. Then, you can introduce the second version of the counter.

2023-02-28 19:33 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +This [simple counter example](https://github.com/casper-ecosystem/counter/blob/57e3912735f93e1d0f667b936675964ecfdc6594/contract-v2/src/main.rs#L105) shows you a contract package that can be versione
The intention is to point to version 1 of the contract package, not the contract-v2. Please update the link and the explanation to clarify this intention.

2023-02-28 19:33 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +Installing contract-v1 as shown in the [counter tutorial](/dapp-dev-guide/tutorials/counter-testnet) is a prerequisite before installing contract-v2.
We already have this in the prerequisites. You could add this note there and remove it from here.

2023-02-28 19:33 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +- contract-v2 is the contract with the new entry point called `counter_decrement`.
This explanation seems to fit better somewhere in the introduction. Here we can simplify and point only to the second version of the contract. 
When you refer to the Wasm files, say "contract-v1.wasm" or "the first version of the contract".

2023-02-28 19:33 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +Installing contract-v1 as shown in the [counter tutorial](/dapp-dev-guide/tutorials/counter-testnet) is a prerequisite before installing contract-v2.
You will also need to fix the links in this file.

2023-02-28 19:33 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +    --session-path ./contract-v1/target/wasm32-unknown-unknown/release/counter-v2.wasm
The session path here seems to be incorrect. Please check the command.

2023-02-28 19:33 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +Now, let's deploy version 2 of the contract, which will add the `counter_decrement` entry point to an existing contract package on the chain.
We have talked about using "install" instead of "deploy". Also, use directives instead of "let's" or "we ...".
The entry point is not added to the package; it is added to the contract.
I think we are using entry-point in the docs, please double check.
```suggestion
Next, install the second contract version on the chain. This version contains the `counter_decrement` entry-point.
```

2023-02-28 19:33 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
>  ### Step 5. Verify your changes
Here you need to talk about the tests already included in the counter repository.
Then, you can also talk about using the CLI to test the changes. But, you will need to cover both ways to test.

2023-02-28 19:33 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +Running the below commands will allow you to observe the new contract entry points.
There is only one new entry point. Use directives.
The Rust CLI should be listed in the prerequisites.
```suggestion
You can test the new entry-point by using the Rust command-line client.
```

2023-02-28 19:33 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +Check the new contract entry points. You should see the _counter_decrement_ entry point now.
```suggestion
Check the contract entry-points. You should see the _counter_decrement_ entry point now.
```

2023-02-28 19:33 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +```bash
For all these commands, add a sample output, that is collapsed and can be expanded.

2023-02-28 19:33 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +Call the new entry point and check the results. The below command will call the _counter_decrement_ entry point using package name.
Avoid duplication, simplify.
```suggestion
Call the new entry point, _counter_decrement_, using the package name and check the results. 
```

2023-02-28 19:33 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +Call the new entry point and check the results. The below command will call the _counter_decrement_ entry point using package name.
Ideally you can also show where the package name was set in the first version of the contract.

2023-02-28 19:33 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +:::
This note should be shorter. Simplify it by not duplicating content detailed in another area of the docs. Link to the calling contracts section instead. Two bullet points with links should be enough.

2023-02-28 19:33 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +Get the NEW state-root-hash:
We repeat this step when we teach or do presentations, but it doesn't work well in written tutorials. Please remove it. It is already highlighted above. 
Review all the occurrences of this command and avoid duplication.
```suggestion
Get the NEW state-root-hash:
```

2023-02-28 19:33 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +After calling the entry-point, the count value should decrement by one. You can verify the decrement by querying the network again, but you will need a new state root hash.
```suggestion
After calling the entry-point, the count value should have been decremented. You can verify it by querying the network again using the new state root hash.
```

2023-02-28 19:33 UTC, ipopescu commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +:::
If you want to keep it, take these steps out of the note.

2023-03-01 11:58 UTC, ShalmaliCL commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +Installing contract-v1 as shown in the [counter tutorial](/dapp-dev-guide/tutorials/counter-testnet) is a prerequisite before installing contract-v2.
I am thinking, the reader may get confused with v1 and v2 terminologies as we have not introduced these yet here in this tutorial. What do you think?

2023-03-01 12:04 UTC, ShalmaliCL commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +- contract-v2 is the contract with the new entry point called `counter_decrement`.
Sounds good.

2023-03-01 12:04 UTC, ShalmaliCL commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +Installing contract-v1 as shown in the [counter tutorial](/dapp-dev-guide/tutorials/counter-testnet) is a prerequisite before installing contract-v2.
Done!

2023-03-01 12:11 UTC, ShalmaliCL commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +This [simple counter example](https://github.com/casper-ecosystem/counter/blob/57e3912735f93e1d0f667b936675964ecfdc6594/contract-v2/src/main.rs#L105) shows you a contract package that can be versione
Done

2023-03-01 12:16 UTC, ShalmaliCL commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +    --session-path ./contract-v1/target/wasm32-unknown-unknown/release/counter-v2.wasm
Fixed it.

2023-03-01 17:01 UTC, closed without merging

2023-03-01 18:02 UTC, ShalmaliCL commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +:::
Done

2023-03-01 18:03 UTC, ShalmaliCL commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +After calling the entry-point, the count value should decrement by one. You can verify the decrement by querying the network again, but you will need a new state root hash.
Done

2023-03-02 04:18 UTC, ShalmaliCL commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
>  ### Step 5. Verify your changes
Changed the sequence. and added details about already included tests in the counter repository.

2023-03-02 05:14 UTC, ShalmaliCL commented
@ipopescu @ACStoneCL - When I synced my fork (ShalmaliCL:main) to casper-network:dev, this PR got automatically closed. 
I am creating a new PR and will try to link this PR to the new one, and will add you guys as a reviewer.
Apologies for the inconvenience caused.

2023-03-02 05:58 UTC, ShalmaliCL commented on source/docs/casper/dapp-dev-guide/tutorials/upgrade-contract.md
> +Get the NEW state-root-hash:
Removed repetitive content.

2023-03-02 05:59 UTC, ShalmaliCL commented on .husky/pre-commit
> +# npm run commit
I am still working on this. Will update here once done.