Add "Deploy & the Deploy Lifecycle" concept
casper-network/docs pull request #961
Opened 2023-03-13 10:55 UTC by andrzej-casper

### What does this PR introduce?

New page "Deploy & the Deploy Lifecycle" under Concepts.

### Additional context

These changes are backported from default branch of [docs-new](https://github.com/casper-network/docs-new) repository, so you can preview them [live here](https://docs-new.casper.network/deploy-and-deploy-lifecycle/).

Original PR authored by @caspermel: https://github.com/casper-network/docs-new/pull/145.

### Checklist

- [x] I ran the docs locally using `yarn install` and `yarn run start`.
- [x] All links (internal and external) have been verified.
- [x] All technical procedures have been tested.

2023-03-14 16:53 UTC, ACStoneCL requested changes
I'm fine with extracting this from the Casper Network overview, but can we use the same PR to remove the duplicate content from [that page?](https://docs.casperlabs.io/concepts/design/casper-design/#execution-semantics-deploys)

2023-03-14 18:15 UTC, ipopescu reviewed
I left some small nits in the headings. As @ACStoneCL requested, please remove the content from the original location. Otherwise, it looks good!

2023-03-14 18:15 UTC, ipopescu commented on source/docs/casper/concepts/deploy-and-deploy-lifecycle.md
> +title: Deploy & Deploy Lifecycle
```suggestion
title: Deploys and the Deploy Lifecycle
```

2023-03-14 18:15 UTC, ipopescu commented on source/docs/casper/concepts/deploy-and-deploy-lifecycle.md
>  # Deploy & the Deploy Lifecycle
```suggestion
# Deploys and the Deploy Lifecycle
```

2023-03-14 18:15 UTC, ipopescu commented on source/docs/casper/concepts/deploy-and-deploy-lifecycle.md
> +## Deploy Lifecycle {#execution-semantics-phases}
```suggestion
## The Deploy Lifecycle {#execution-semantics-phases}
```

2023-03-21 13:24 UTC, caspermel commented
Yes, I agree that the original content should be removed.

2023-03-24 09:52 UTC, merged