Backport account hash explanation
casper-network/docs pull request #965
Opened 2023-03-13 12:21 UTC by andrzej-casper

### What does this PR introduce?

Polished version of types pages, mainly better explanation of _Account Hash_.

### Additional context

These changes are backported from the default branch of [docs-new](https://github.com/casper-network/docs-new) repository.

Original PR authored by @jonas089: https://github.com/casper-network/docs-new/pull/15.

### Checklist

- [x] I ran the docs locally using `yarn install` and `yarn run start`.
- [x] All links (internal and external) have been verified.
- [x] All technical procedures have been tested.

2023-03-14 14:12 UTC, ipopescu requested changes

2023-03-14 14:12 UTC, ipopescu commented on source/docs/casper/developers/json-rpc/types_chain.md
> +The AccountHash is a Hex-encoding of the PublicKey and therefore can be viewed as an address.
We have been cautious about the term `address` in the documentation. See issues https://github.com/casper-network/docs/issues/404, https://github.com/casper-network/docs/issues/95. Also, see this definition in the [docs](https://docs.casperlabs.io/concepts/accounts-and-keys/).
```suggestion
The AccountHash is a 32-byte hash derived from a supported PublicKey. Its role is to standardize keys that can vary in length.
```

2023-03-23 15:30 UTC, ipopescu approved these changes
Thank you, @jonas089!

2023-03-23 15:35 UTC, ipopescu commented on source/docs/casper/developers/json-rpc/types_chain.md
> +The AccountHash is a Hex-encoding of the PublicKey and therefore can be viewed as an address.
Please take a look. I am not sure why this was resolved. I don't see a new commit.

2023-03-23 16:32 UTC, jonas089 commented
Thanks, @ipopescu.
Now everything should be committed.

2023-03-23 16:34 UTC, ipopescu approved these changes
LGTM!

2023-03-23 16:49 UTC, merged