Polished intro to SDKs
casper-network/docs pull request #966
Opened 2023-03-13 12:36 UTC by andrzej-casper

### What does this PR fix/introduce?

Polishes existing Building-dApps/Intro to SDKs.

### Additional context

These changes are backported from the default branch of [docs-new](https://github.com/casper-network/docs-new) repository, so you can preview them [live here](https://docs-new.casper.network/sdk/).

Original PR authored by @dylanireland: https://github.com/casper-network/docs-new/pull/148.

### Checklist

- [x] I ran the docs locally using `yarn install` and `yarn run start`.
- [x] All links (internal and external) have been verified.
- [x] All technical procedures have been tested.

2023-03-17 21:24 UTC, ipopescu requested changes

2023-03-17 21:24 UTC, ipopescu commented on source/docs/casper/developers/dapps/sdk/index.md
> +title: Introduction to SDKs
What is the reasoning behind changing the title? I think it would be best to keep the original one.
This is not really an introduction to what SDKs are... but just listing the available libraries.

2023-03-17 21:24 UTC, ipopescu commented on source/docs/casper/developers/dapps/sdk/index.md
> -Each such third party is solely responsible for the SDK it provides, any warranties (to the extent that such warranties have not been disclaimed), and for any claims you may have relating to your acc
Please bring this disclaimer back up, it's important for readers to see it before they jump into the links.

2023-03-17 21:24 UTC, ipopescu commented on source/docs/casper/developers/dapps/sdk/index.md
> +Each of these SDKs can be used to build dApps. For browser interaction you can use the JavaScript SDK, for desktop applications there is C#, Java, etc. Click the link on your preferred SDK to learn h
```suggestion
Each of these SDKs can be used to build dApps. For browser interaction, you can use the JavaScript SDK; for desktop applications, there are C# and Java SDKs. Click the link on your preferred SDK to learn how to use it in dApp development. To delve into the source code, you may visit the SDKs' Github repositories.
```

2023-03-17 21:24 UTC, ipopescu commented on source/docs/casper/developers/dapps/sdk/index.md
> -| Scala SDK | [casper-scala-sdk](https://github.com/abahmanem/casper-scala-sdk) | [M. Abahmane](https://github.com/abahmanem) |
Please revert changes to this table. It seems to be old content that wasn't merged correctly. See PR [896](https://github.com/casper-network/docs/pull/896).

2023-03-28 17:37 UTC, dylanireland commented on source/docs/casper/developers/dapps/sdk/index.md
> +title: Introduction to SDKs
My mistake, I thought I'd done this. The title is now reverted.

2023-03-28 18:22 UTC, ipopescu commented on source/docs/casper/developers/dapps/sdk/index.md
> +# Introduction to SDKs
The title didn't revert for some reason, so I will do it.
```suggestion
# SDK Client Libraries
```

2023-03-28 18:56 UTC, ACStoneCL approved these changes
For some reason, Github is still showing the new title for me in the "Files changed" tab, but I see the commits that revert it.

May need to take another look after merging - but otherwise LGTM.

2023-03-28 18:57 UTC, merged