Polished getting-started for on-chain code
casper-network/docs pull request #967
Opened 2023-03-13 12:58 UTC by andrzej-casper

### What does this PR fix/introduce?

Polishes getting started section under _Developers - Writing On-Chain Code_.

### Additional context

These changes are backported from the default branch of [docs-new](https://github.com/casper-network/docs-new) repository, so you can preview them [live here](https://docs-new.casper.network/developers/writing-onchain-code/getting-started/).

Original PR authored by @KMCreatesWorlds: https://github.com/casper-network/docs-new/pull/11.

### Checklist

- [x] I ran the docs locally using `yarn install` and `yarn run start`.
- [x] All links (internal and external) have been verified.
- [x] All technical procedures have been tested.

2023-03-17 21:39 UTC, ipopescu requested changes

2023-03-17 21:39 UTC, ipopescu commented on source/docs/casper/developers/writing-onchain-code/getting-started.md
> -We recommend setting up the rust-toolchain in the top level directory of your project.
Why was this content removed?

2023-03-17 21:39 UTC, ipopescu commented on source/docs/casper/developers/writing-onchain-code/getting-started.md
> +- Vim
Perhaps adding links would be useful.

2023-03-17 21:39 UTC, ipopescu commented on source/docs/casper/developers/writing-onchain-code/getting-started.md
> +You can use whatever IDE you feel the most comfortable using. In all the exercises and tutorials, we will be using Visual Studio Code as it is the most popular one and has a lot of additional extensi
```suggestion
You can use any IDE you wish. This documentation and examples use [Visual Studio Code (VSC)](https://code.visualstudio.com), a popular IDE with many extensions that might be helpful during development.
```

2023-03-17 21:39 UTC, ipopescu commented on source/docs/casper/developers/writing-onchain-code/getting-started.md
> +The easiest way of installing the VSC is to get it from the [official site](https://code.visualstudio.com):
Include the link above for conciseness. 
```suggestion

```

2023-03-17 21:39 UTC, ipopescu commented on source/docs/casper/developers/writing-onchain-code/getting-started.md
> +During the exercises and tutorials, ways to leverage the extensions will be briefly described.
I've simplified the list and applied the formatting we use elsewhere.
Let's not promise this: "During the exercises and tutorials, ways to leverage the extensions will be briefly described." Instead, let's add it wherever possible and remove it from here.
Is it possible to add links to the extensions?
```suggestion
- `CodeLLDB` – An important extension for debugging Rust code
- `rust-analyzer` – The official Rust language extension
- `Better TOML` – Support for formatting TOML files
- `crates` – An extension to help manage crates
- `Error Lens` – Enhances the programming experience by highlighting syntax errors
```

2023-03-17 21:39 UTC, ipopescu commented on source/docs/casper/developers/writing-onchain-code/getting-started.md
> +<p align="center"><img src={useBaseUrl("/image/introduction/download-vscode.png")} alt="download-vscode" width="400"/></p>
The link already included should be enough. I don't think we need this image, it doesn't add a lot of information. 
```suggestion

```

2023-03-21 23:19 UTC, KMCreatesWorlds commented on source/docs/casper/developers/writing-onchain-code/getting-started.md
> -We recommend setting up the rust-toolchain in the top level directory of your project.
It was previously removed because during automatic creation using the cargo the nightly is referenced and everything works correctly. This section might be confusing for new people. I would suggest that instead of linking the toolchains etc. just include installing the nightly "rustup toolchain install nightly" because this is what's needed. This step has to be also only made for manual project structure.

2023-03-22 12:27 UTC, ipopescu commented on source/docs/casper/developers/writing-onchain-code/getting-started.md
> -We recommend setting up the rust-toolchain in the top level directory of your project.
Ok. Please add what you are proposing as part of this PR, so it is easier to see the final page as you propose it. Then we can resolve this comment.

2023-03-28 18:33 UTC, ipopescu commented
@andrzej-casper, this PR seems to be in progress still. Please let us know when it's ready for another round of reviews.

2023-04-04 14:24 UTC, ACStoneCL commented on source/docs/casper/developers/writing-onchain-code/getting-started.md
> +Casper's blockchain is built upon the Rust programming language and compiles down to WebAssembly. This guide will walk you through the steps to set up your development environment and build your firs
```suggestion
Casper's blockchain is built upon the Rust programming language and compiles down to WebAssembly. This guide will walk you through the steps to set up your development environment and write your first contract.
```

2023-04-04 14:24 UTC, ACStoneCL commented on source/docs/casper/developers/writing-onchain-code/getting-started.md
> -We recommend setting up the rust-toolchain in the top level directory of your project.
We should bring this back in, because using `cargo casper` inserts the toolchain into the project structure.

We should at least refer to it, as it's included. Otherwise, people using cargo casper will see it and be confused by it's inclusion.

2023-04-04 14:24 UTC, ACStoneCL commented on source/docs/casper/developers/writing-onchain-code/getting-started.md
> +We also provide a [Casper command-line client](../prerequisites.md#the-casper-command-line-client), a Rust CLI tool that can help you transmit deploys and install code on-chain.
```suggestion
We also provide a [Casper command-line client](../prerequisites.md#the-casper-command-line-client), a Rust CLI tool that can help you send deploys and install code on-chain.
```

2023-04-04 14:24 UTC, ACStoneCL commented on source/docs/casper/developers/writing-onchain-code/getting-started.md
> +During the exercises and tutorials, ways to leverage the extensions will be briefly described.
Developers can make their own choices when it comes to plugins and tools - this is a Rust question more than a Casper question.

We should focus on the Casper-centric aspects of Rust and this list is ultimately unnecessary and a matter of taste.

2023-04-05 14:57 UTC, andrzej-casper commented
I backported Jonas improvements from https://github.com/casper-network/docs-new/pull/179.

2023-04-06 21:46 UTC, ipopescu reviewed
This PR still needs some updates, @jonas089, @andrzej-casper. Please check out the open comments and suggestions.

2023-04-06 21:46 UTC, ipopescu commented on source/docs/casper/developers/writing-onchain-code/getting-started.md
> +The best and fastest way to set up a Casper Rust Smart Contract project is to use `cargo-casper`. When you use this, it will set the project up with a simple contract, a runtime environment and a tes
```suggestion
The best and fastest way to set up a Casper Rust project is to use `cargo casper`. Using this will create a simple contract, a runtime environment, and a testing framework with a simple test. _Cargo_ is a build system and package manager for Rust (much like _pip_ if you are familiar with Python, or _npm_ and _yarn_ for those familiar with Javascript). It is also possible to use this configuration in your CI/CD pipeline.
```

2023-04-11 15:02 UTC, jonas089 commented
I haven't received notifications for this branch, so I'm catching up now that I saw the changes.

2023-04-11 15:12 UTC, ipopescu commented
Sounds good, @jonas089, let us know when you are ready.

2023-04-13 12:01 UTC, ipopescu approved these changes
LGTM!

2023-04-13 12:43 UTC, merged