Polish Writing Basic Smart Contract page
casper-network/docs pull request #969
Opened 2023-03-13 14:10 UTC by andrzej-casper

### What does this PR fix/introduce?

Polishes _Writing Basic Smart Contract_ under _Developers - Writing On-Chain Code_.

### Additional context

These changes are backported from the default branch of [docs-new](https://github.com/casper-network/docs-new) repository, so you can preview them [live here](https://docs-new.casper.network/developers/writing-onchain-code/simple-contract/).

Original PR authored by @KMCreatesWorlds: https://github.com/casper-network/docs-new/pull/123.

### Checklist

- [x] I ran the docs locally using `yarn install` and `yarn run start`.
- [x] All links (internal and external) have been verified.
- [x] All technical procedures have been tested.

2023-03-17 21:14 UTC, ipopescu requested changes

2023-03-17 21:14 UTC, ipopescu commented on source/docs/casper/developers/writing-onchain-code/simple-contract.md
> +The project structure will be different while designing the full stack architecture. This will be expanded upon while describing the dApps.
Please comment out this line until the new page is created. This is a simple example just to get someone started. For a more thorough example, a link can be added here when the guide is available.

2023-03-17 21:14 UTC, ipopescu commented on source/docs/casper/developers/writing-onchain-code/simple-contract.md
> +Structure created automatically with `cargo casper` contains everything that is needed to start coding.
Actually, this section is for developers who want to set things up from scratch; otherwise, we wouldn't include it.
I would not advise against this section, but we could move it after the  "Creating the Project Automatically" section.
```suggestion
If you are a beginner, [creating the structure automatically](#creating-the-project-automatically) with `cargo casper` contains everything you need to start coding.
```

2023-03-17 21:14 UTC, ipopescu commented on source/docs/casper/developers/writing-onchain-code/simple-contract.md
> +
This page assumes that readers have a basic understanding of Rust. I recommend moving this section to a new guide or page that could be "An introduction to Rust", "Important Rust Syntax", or "Tips for Rust Contracts", under Resources.
It would also be good to include references to the Rust Book or Rust by Example. However, that is another topic that would be better placed as a resource.

2023-04-05 13:59 UTC, andrzej-casper commented on source/docs/casper/developers/writing-onchain-code/simple-contract.md
> +The project structure will be different while designing the full stack architecture. This will be expanded upon while describing the dApps.
@jonas089 This still has to be addressed.

2023-04-05 14:02 UTC, andrzej-casper commented on source/docs/casper/developers/writing-onchain-code/simple-contract.md
> +
@KMCreatesWorlds This still has to be addressed.

2023-04-05 14:04 UTC, andrzej-casper commented
I backported Jonas improvements from https://github.com/casper-network/docs-new/pull/180.

2023-04-06 20:34 UTC, ipopescu commented on source/docs/casper/developers/writing-onchain-code/simple-contract.md
> +
Ok. If you have an issue number, please place it here, and we can resolve the comment so that this request is captured.

2023-04-06 20:34 UTC, ipopescu commented on source/docs/casper/developers/writing-onchain-code/simple-contract.md
> +The project structure will be different while designing the full stack architecture. This will be expanded upon while describing the dApps.
Ideally, we only include this line once the guide is ready, but if you have an issue number, please place it here, and we can resolve the comment.

2023-04-06 20:37 UTC, ipopescu commented on source/docs/casper/developers/writing-onchain-code/simple-contract.md
> +Structure created automatically with `cargo casper` contains everything that is needed to start coding.
Thanks. The commit suggestion wasn't applied, though. I will apply it.

2023-04-06 21:35 UTC, ipopescu approved these changes
Nice work, TT!

I did a final editing pass. If it's ok with you, please merge this PR.

2023-04-10 19:17 UTC, merged