Add "Cross-Contract Communication" tutorial
casper-network/docs pull request #995
Opened 2023-03-27 19:23 UTC by andrzej-casper

### What does this PR introduce?

New advanced tutorial "Cross-Contract Communication".

### Additional context

These changes are backported from the default branch of [docs-new](https://github.com/casper-network/docs-new) repository, so you can preview them [live here](https://staging.docs.casper.network/resources/tutorials/advanced/cross-contract/). As agreed with @darthsiroftardis, tutorials review can be handled directly by Tiger Team. However, we need approval here, just to make sure Docs team is aware of newly created content.

Original PR authored by @KMCreatesWorlds: https://github.com/casper-network/docs-new/pull/165.

### Checklist

- [x] Docs are successfully building - `yarn install && yarn run build`.
- [x] All technical procedures have been tested.

2023-03-28 23:49 UTC, RitaMAllenCA commented
@andrzej-casper was an issue opened for this?  I don't see one.   Please add #<ticket number> to the description of the PR so we can attach them, thank you.

2023-03-29 16:26 UTC, ACStoneCL requested changes
In addition to my review, I'd like one of our smart contract developers to review both my comments and the document itself to ensure that terminology is consistent with that used in Casper development.

2023-03-29 16:26 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/advanced/cross-contract.md
> +This would be the easiest implementation of the call function. There is only one entry point which accepts the key `contract2` of type `String` and the key `hello_world_contract` of the type `Key`. T
```suggestion
This would be the easiest implementation of the `call` entry point. There is only one entry point which accepts the key `contract2` of type `String` and the key `hello_world_contract` of the type `Key`. There aren't any named keys which will be saved in the contract's context. The contract is then stored in global state and placed as a named key in the account's context.
```

2023-03-29 16:26 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/advanced/cross-contract.md
> +Observing the deploy, we can see that it has been successful:
```suggestion
Observing the deploy, we can see that it succeeded:
```

2023-03-29 16:26 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/advanced/cross-contract.md
> +As we have now managed to deploy two contracts, we can call the endpoint of this contract, passing appropriate arguments to the function.
```suggestion
As we have now managed to deploy two contracts, we can call the entry point of this contract, passing appropriate arguments to the function. 
```

2023-03-29 16:26 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/advanced/cross-contract.md
> +`--session-arg` "hello world_contract:Key= ..."  the hash of the contract which we want to call from within the contract identified by the session-hash.
```suggestion
`--session-arg` "hello world_contract:Key= ..." - the hash of the contract which we want to call from within the contract identified by the session-hash.
```

2023-03-29 16:26 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/advanced/cross-contract.md
> +After the deploy finishes successfuly, you should see a similar outcome to the following:
```suggestion
After the deploy finishes successfully, you should see a similar outcome to the following:
```

2023-03-29 16:26 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/advanced/cross-contract.md
> +With this we have succesfully built a cross contract communication between two contracts.
```suggestion
With this we have succeeded in cross-contract communication between two contracts.
```

2023-03-29 16:26 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/advanced/cross-contract.md
> +- Developed two Rust contracts on the Casper Network where one smart contract is calling an entry point of the second smart contract
```suggestion
- Developed two Rust contracts on a Casper network, where one smart contract is calling an entry point of the second smart contract
```

2023-03-29 16:26 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/advanced/cross-contract.md
> +- Called an entry point on one contract from the other contract, passing a value as argument to this entry point.
```suggestion
- Called an entry point on one contract from the other contract, passing a value as an argument to this entry point.
```

2023-03-31 12:26 UTC, KMCreatesWorlds commented on source/docs/casper/resources/tutorials/advanced/cross-contract.md
> +This tutorial covers some variations of cross-contract communication. Most complex scenarios use cross-contract communication, so it is crucial to understand how this works. It is best explained usin
The example with Uniswap was to present a tangible use case that is used in the real world. I do know that we don't have an example of a native DEX on Casper. A lot of people in Crypto/Blockchain are however familiar with Uniswap and this was just to make a point, that in those cases Cross-Contract Communication is used.

2023-03-31 12:30 UTC, KMCreatesWorlds commented on source/docs/casper/resources/tutorials/advanced/cross-contract.md
> +The Pair smart contract is used to perform operations like mint or burn on a created pair of tokens.
For this, it is not necessary to know how Uniswap works for providing liquidity/creating pairs. The point that I am making is that the Factory contract creates the Pair contract and both contracts: Factory and Pair, have different responsibilities, but it might be necessary to send information between both of them.

2023-04-05 17:29 UTC, ACStoneCL reviewed
Comments are from review conducted over Zoom, and include tech review:

Comments across the doc:
Capitalize the start of each code comment.
Use of the term "parameters" should be changed to "runtime arguments"
Change "standard contract structure" to "default contract structure"

2023-04-05 17:29 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/advanced/cross-contract.md
> +We can use the supplied deploy hash, `af42bc6dbc58f677d138eb968d897f965f1ed118a40980bc16efbcc2a0c71832` to find this contract using a block explorer. When viewed through the explorer, the status of t
We would suggest making this tutorial specific to the Rust CLI rather than including the block explorer here.

2023-04-05 17:29 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/advanced/cross-contract.md
> +    // create a new vector - this will be the signature of the entry point
```suggestion
    // Create the list of required runtime arguments for the given entry point.
```

2023-04-05 17:29 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/advanced/cross-contract.md
> +    // add the entry point to the entry points object
```suggestion
    // Add the entry point metadata definition.
```

2023-04-05 17:29 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/advanced/cross-contract.md
> +This would be the easiest implementation of the `call` entry point. There is only one entry point which accepts the key `contract2` of type `String` and the key `hello_world_contract` of the type `Ke
```suggestion
This would be the easiest implementation of the `call` entry point. There is only one entry point which accepts the key `contract2` of type `String` and the key `hello_world_contract` of the type `Key`. There aren't any named keys which will be saved in the contract's context. The contract is then stored in global state and placed as an entry within the account's named keys.
```

2023-04-05 17:29 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/advanced/cross-contract.md
> +Now that we have defined the `call_contract_2` entry point, we must implement the corresponding function. This entry point will take the second contract hash as an argument and call the entry point `
```suggestion
Now that we have defined the metadata for the `call_contract_2` entry point, we must now define the entry point itself. This entry point will take the second contract hash as an argument and call the entry point `update_msg`. It will then pass a message to the second contract as a parameter, which will be stored in that contract’s context.
```

2023-04-05 17:29 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/advanced/cross-contract.md
> +    // get the contract hash from the named arguments passed to the call
```suggestion
    // get the contract hash from the named arguments passed to the `call_contract_2` entry point.
```

2023-04-05 17:29 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/advanced/cross-contract.md
> +    // Call the update_msg endpoint on the other contract with the parameter values
```suggestion
    // Call the update_msg entry point on the other contract with the parameter values
```

2023-04-05 17:29 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/advanced/cross-contract.md
> +    // the contract is stored in the global state
```suggestion
    // the contract is stored in global state
```

2023-04-05 17:29 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/advanced/cross-contract.md
> +The output of the deployment is:
```suggestion
The result of invoking the `put-deploy` subcommand is:
```

2023-04-05 17:29 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/advanced/cross-contract.md
> +Observing the deploy, we can see that it succeeded:
We can use screenshots from the Rust CLI, to stay consistent with the overall tutorial.

2023-04-05 17:29 UTC, ACStoneCL commented on source/docs/casper/resources/tutorials/advanced/cross-contract.md
> +- Discussed why cross-contract communication is sometimes necessary
```suggestion
```

2023-04-06 07:48 UTC, KMCreatesWorlds commented on source/docs/casper/resources/tutorials/advanced/cross-contract.md
> +There is a distinction between storing data in a contract’s `NamedKeys` and using a dictionary. Dictionaries can be used to store dApp-centric data, but they are not a SQL database and should only be
This sentence is trying to point out why it is good to be mindful which data should be stored in the Named Keys and which in the Dictionaries. If a developer is inexperienced then he/she might try to store a lot of information in the Named Keys but this wouldn't be good from the design point of view.

2023-04-11 15:18 UTC, ipopescu commented
@KMCreatesWorlds and @andrzej-casper, is this PR ready for another review? If so, could you please re-request it or let us know explicitly?

2023-04-13 14:36 UTC, andrzej-casper commented
Related task: https://github.com/casper-network/docs-new/issues/128.

2023-04-13 16:10 UTC, KMCreatesWorlds commented on source/docs/casper/resources/tutorials/advanced/cross-contract.md
> +There is a distinction between storing data in a contract’s `NamedKeys` and using a dictionary. Dictionaries can be used to store dApp-centric data, but they are not a SQL database and should only be
Add link to the Dictionaries page

2023-04-17 11:29 UTC, KMCreatesWorlds commented on source/docs/casper/resources/tutorials/advanced/cross-contract.md
> +There is a distinction between storing data in a contract’s `NamedKeys` and using a dictionary. Dictionaries can be used to store dApp-centric data, but they are not a SQL database and should only be
Link was added

2023-04-17 11:29 UTC, KMCreatesWorlds commented on source/docs/casper/resources/tutorials/advanced/cross-contract.md
> +We can use the supplied deploy hash, `af42bc6dbc58f677d138eb968d897f965f1ed118a40980bc16efbcc2a0c71832` to find this contract using a block explorer. When viewed through the explorer, the status of t
All of the block explorer parts were changed to the CLI

2023-04-17 11:29 UTC, KMCreatesWorlds commented on source/docs/casper/resources/tutorials/advanced/cross-contract.md
> +Observing the deploy, we can see that it succeeded:
Rust CLI was used instead of the block explorer screenshots

2023-04-17 13:40 UTC, ACStoneCL approved these changes
All suggestions and requests are resolved and document is in compliance with style requirements.

2023-04-17 14:43 UTC, merged